#include "plugin.hpp"
#include "host_classes.hpp"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE MathPlugin* MathPlugin_create() {
    return new MathPlugin();
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_destroy(MathPlugin* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int MathPlugin_get_counter(MathPlugin* ptr) {
    return ptr->counter;
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_set_counter(MathPlugin* ptr, int val) {
    ptr->counter = val;
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_increment(MathPlugin* ptr) {
    ptr->increment();
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_decrement(MathPlugin* ptr) {
    ptr->decrement();
}

EMSCRIPTEN_KEEPALIVE int MathPlugin_multiply(MathPlugin* ptr, int arg0, int arg1) {
    auto _ret = ptr->multiply(arg0, arg1);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_do_logging(MathPlugin* ptr, long long unsigned int arg0) {
    ptr->do_logging(arg0);
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE void Shape_destroy(Shape* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Shape_sides(Shape* ptr) {
    auto _ret = ptr->sides();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Shape_area(Shape* ptr) {
    auto _ret = ptr->area();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Shape_describe(Shape* ptr) {
    auto _ret = ptr->describe();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Rect* Rect_create() {
    return new Rect();
}

EMSCRIPTEN_KEEPALIVE void Rect_destroy(Rect* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Rect_get_w(Rect* ptr) {
    return ptr->w;
}

EMSCRIPTEN_KEEPALIVE void Rect_set_w(Rect* ptr, int val) {
    ptr->w = val;
}

EMSCRIPTEN_KEEPALIVE int Rect_get_h(Rect* ptr) {
    return ptr->h;
}

EMSCRIPTEN_KEEPALIVE void Rect_set_h(Rect* ptr, int val) {
    ptr->h = val;
}

EMSCRIPTEN_KEEPALIVE int Rect_sides(Rect* ptr) {
    auto _ret = ptr->sides();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Rect_area(Rect* ptr) {
    auto _ret = ptr->area();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Rect_describe(Rect* ptr) {
    auto _ret = ptr->describe();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Square* Square_create() {
    return new Square();
}

EMSCRIPTEN_KEEPALIVE void Square_destroy(Square* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Square_get_w(Square* ptr) {
    return ptr->w;
}

EMSCRIPTEN_KEEPALIVE void Square_set_w(Square* ptr, int val) {
    ptr->w = val;
}

EMSCRIPTEN_KEEPALIVE int Square_get_h(Square* ptr) {
    return ptr->h;
}

EMSCRIPTEN_KEEPALIVE void Square_set_h(Square* ptr, int val) {
    ptr->h = val;
}

EMSCRIPTEN_KEEPALIVE int Square_describe(Square* ptr) {
    auto _ret = ptr->describe();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Square_sides(Square* ptr) {
    auto _ret = ptr->sides();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Square_area(Square* ptr) {
    auto _ret = ptr->area();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Walker* Walker_create() {
    return new Walker();
}

EMSCRIPTEN_KEEPALIVE void Walker_destroy(Walker* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Walker_walk(Walker* ptr, int arg0) {
    auto _ret = ptr->walk(arg0);
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Swimmer* Swimmer_create() {
    return new Swimmer();
}

EMSCRIPTEN_KEEPALIVE void Swimmer_destroy(Swimmer* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Swimmer_swim(Swimmer* ptr, int arg0) {
    auto _ret = ptr->swim(arg0);
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Duck* Duck_create() {
    return new Duck();
}

EMSCRIPTEN_KEEPALIVE void Duck_destroy(Duck* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Duck_walk(Duck* ptr, int arg0) {
    auto _ret = ptr->walk(arg0);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Duck_swim(Duck* ptr, int arg0) {
    auto _ret = ptr->swim(arg0);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Duck_fly(Duck* ptr) {
    auto _ret = ptr->fly();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Entity* Entity_create() {
    return new Entity();
}

EMSCRIPTEN_KEEPALIVE void Entity_destroy(Entity* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Entity_id(Entity* ptr) {
    auto _ret = ptr->id();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Entity_kind(Entity* ptr) {
    auto _ret = ptr->kind();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Named* Named_create() {
    return new Named();
}

EMSCRIPTEN_KEEPALIVE void Named_destroy(Named* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Named_kind(Named* ptr) {
    auto _ret = ptr->kind();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Named_name_len(Named* ptr) {
    auto _ret = ptr->name_len();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Named_id(Named* ptr) {
    auto _ret = ptr->id();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Tagged* Tagged_create() {
    return new Tagged();
}

EMSCRIPTEN_KEEPALIVE void Tagged_destroy(Tagged* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Tagged_id(Tagged* ptr) {
    auto _ret = ptr->id();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Tagged_tag_count(Tagged* ptr) {
    auto _ret = ptr->tag_count();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Tagged_kind(Tagged* ptr) {
    auto _ret = ptr->kind();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Widget* Widget_create() {
    return new Widget();
}

EMSCRIPTEN_KEEPALIVE void Widget_destroy(Widget* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Widget_total(Widget* ptr) {
    auto _ret = ptr->total();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Widget_kind(Widget* ptr) {
    auto _ret = ptr->kind();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Widget_name_len(Widget* ptr) {
    auto _ret = ptr->name_len();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Widget_id(Widget* ptr) {
    auto _ret = ptr->id();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Widget_tag_count(Widget* ptr) {
    auto _ret = ptr->tag_count();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Bird* Bird_create() {
    return new Bird();
}

EMSCRIPTEN_KEEPALIVE void Bird_destroy(Bird* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Bird_legs(Bird* ptr) {
    auto _ret = ptr->legs();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Bird_sound_id(Bird* ptr) {
    auto _ret = ptr->sound_id();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Bird_describe(Bird* ptr) {
    auto _ret = ptr->describe();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE void Bird_attach(Bird* ptr, long long unsigned int arg0) {
    ptr->attach(arg0);
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE Thrower* Thrower_create() {
    return new Thrower();
}

EMSCRIPTEN_KEEPALIVE void Thrower_destroy(Thrower* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int Thrower_risky(Thrower* ptr, int arg0) {
    auto _ret = ptr->risky(arg0);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Thrower_divide_via_host(Thrower* ptr, long long unsigned int arg0, int arg1, int arg2) {
    auto _ret = ptr->divide_via_host(arg0, arg1, arg2);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Thrower_add_via_host(Thrower* ptr, long long unsigned int arg0, int arg1, int arg2) {
    auto _ret = ptr->add_via_host(arg0, arg1, arg2);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int Thrower_divide_via_shared_host(Thrower* ptr, long long unsigned int arg0, int arg1, int arg2) {
    auto _ret = ptr->divide_via_shared_host(arg0, arg1, arg2);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE void Thrower_crash(Thrower* ptr) {
    ptr->crash();
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE MemoryProbe* MemoryProbe_create() {
    return new MemoryProbe();
}

EMSCRIPTEN_KEEPALIVE void MemoryProbe_destroy(MemoryProbe* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int MemoryProbe_alloc_block(MemoryProbe* ptr, int arg0) {
    auto _ret = ptr->alloc_block(arg0);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int MemoryProbe_free_all(MemoryProbe* ptr) {
    auto _ret = ptr->free_all();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int MemoryProbe_block_count(MemoryProbe* ptr) {
    auto _ret = ptr->block_count();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int MemoryProbe_pages(MemoryProbe* ptr) {
    auto _ret = ptr->pages();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int MemoryProbe_grow(MemoryProbe* ptr, int arg0) {
    auto _ret = ptr->grow(arg0);
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE StorageClient* StorageClient_create() {
    return new StorageClient();
}

EMSCRIPTEN_KEEPALIVE void StorageClient_destroy(StorageClient* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int StorageClient_save_number(StorageClient* ptr, int arg0) {
    auto _ret = ptr->save_number(arg0);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int StorageClient_load_number(StorageClient* ptr) {
    auto _ret = ptr->load_number();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int StorageClient_write_blob(StorageClient* ptr, int arg0) {
    auto _ret = ptr->write_blob(arg0);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int StorageClient_blob_checksum(StorageClient* ptr) {
    auto _ret = ptr->blob_checksum();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int StorageClient_try_write(StorageClient* ptr, int arg0, int arg1) {
    auto _ret = ptr->try_write(arg0, arg1);
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int StorageClient_remove_blob(StorageClient* ptr) {
    auto _ret = ptr->remove_blob();
    return _ret;
}

EMSCRIPTEN_KEEPALIVE int StorageClient_used_bytes(StorageClient* ptr) {
    auto _ret = ptr->used_bytes();
    return _ret;
}

} // extern "C"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE ContainerPlugin* ContainerPlugin_create() {
    return new ContainerPlugin();
}

EMSCRIPTEN_KEEPALIVE void ContainerPlugin_destroy(ContainerPlugin* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE void ContainerPlugin_process_containers(ContainerPlugin* ptr, uint32_t arg0, uint32_t arg1) {
    using BaseT_arg0 = std::remove_reference_t<std::vector<int>&>;
    using ValT_arg0 = BaseT_arg0::value_type;
    uint32_t* arg0_struct = reinterpret_cast<uint32_t*>(arg0);
    ValT_arg0* arg0_data = reinterpret_cast<ValT_arg0*>(arg0_struct[0]);
    uint32_t arg0_len = arg0_struct[1];
    BaseT_arg0 local_arg0(arg0_data, arg0_data + arg0_len);
    using BaseT_arg1 = std::remove_reference_t<std::map<int, int>&>;
    using K_arg1 = BaseT_arg1::key_type;
    using V_arg1 = BaseT_arg1::mapped_type;
    using PairT_arg1 = std::pair<K_arg1, V_arg1>;
    uint32_t* arg1_struct = reinterpret_cast<uint32_t*>(arg1);
    PairT_arg1* arg1_data = reinterpret_cast<PairT_arg1*>(arg1_struct[0]);
    uint32_t arg1_len = arg1_struct[1];
    BaseT_arg1 local_arg1(arg1_data, arg1_data + arg1_len);
    ptr->process_containers(local_arg0, local_arg1);
    ValT_arg0* new_arg0_data = (ValT_arg0*) cerridwen::plugin::allocate(local_arg0.size() * sizeof(ValT_arg0));
    std::memcpy((void*)new_arg0_data, local_arg0.data(), local_arg0.size() * sizeof(ValT_arg0));
    arg0_struct[0] = reinterpret_cast<uint32_t>(new_arg0_data);
    arg0_struct[1] = local_arg0.size();
    std::vector<PairT_arg1> new_arg1_flat(local_arg1.begin(), local_arg1.end());
    PairT_arg1* new_arg1_data = (PairT_arg1*) cerridwen::plugin::allocate(new_arg1_flat.size() * sizeof(PairT_arg1));
    std::memcpy((void*)new_arg1_data, new_arg1_flat.data(), new_arg1_flat.size() * sizeof(PairT_arg1));
    arg1_struct[0] = reinterpret_cast<uint32_t>(new_arg1_data);
    arg1_struct[1] = new_arg1_flat.size();
}

EMSCRIPTEN_KEEPALIVE void ContainerPlugin_process_other_containers(ContainerPlugin* ptr, uint32_t arg0, uint32_t arg1, uint32_t arg2, uint32_t arg3, uint32_t arg4) {
    using BaseT_arg0 = std::remove_reference_t<std::set<int>&>;
    using ValT_arg0 = BaseT_arg0::value_type;
    uint32_t* arg0_struct = reinterpret_cast<uint32_t*>(arg0);
    ValT_arg0* arg0_data = reinterpret_cast<ValT_arg0*>(arg0_struct[0]);
    uint32_t arg0_len = arg0_struct[1];
    BaseT_arg0 local_arg0(arg0_data, arg0_data + arg0_len);
    using BaseT_arg1 = std::remove_reference_t<std::list<int>&>;
    using ValT_arg1 = BaseT_arg1::value_type;
    uint32_t* arg1_struct = reinterpret_cast<uint32_t*>(arg1);
    ValT_arg1* arg1_data = reinterpret_cast<ValT_arg1*>(arg1_struct[0]);
    uint32_t arg1_len = arg1_struct[1];
    BaseT_arg1 local_arg1(arg1_data, arg1_data + arg1_len);
    using BaseT_arg2 = std::remove_reference_t<std::deque<int>&>;
    using ValT_arg2 = BaseT_arg2::value_type;
    uint32_t* arg2_struct = reinterpret_cast<uint32_t*>(arg2);
    ValT_arg2* arg2_data = reinterpret_cast<ValT_arg2*>(arg2_struct[0]);
    uint32_t arg2_len = arg2_struct[1];
    BaseT_arg2 local_arg2(arg2_data, arg2_data + arg2_len);
    using BaseT_arg3 = std::remove_reference_t<std::unordered_set<int>&>;
    using ValT_arg3 = BaseT_arg3::value_type;
    uint32_t* arg3_struct = reinterpret_cast<uint32_t*>(arg3);
    ValT_arg3* arg3_data = reinterpret_cast<ValT_arg3*>(arg3_struct[0]);
    uint32_t arg3_len = arg3_struct[1];
    BaseT_arg3 local_arg3(arg3_data, arg3_data + arg3_len);
    using BaseT_arg4 = std::remove_reference_t<std::unordered_map<int, int>&>;
    using K_arg4 = BaseT_arg4::key_type;
    using V_arg4 = BaseT_arg4::mapped_type;
    using PairT_arg4 = std::pair<K_arg4, V_arg4>;
    uint32_t* arg4_struct = reinterpret_cast<uint32_t*>(arg4);
    PairT_arg4* arg4_data = reinterpret_cast<PairT_arg4*>(arg4_struct[0]);
    uint32_t arg4_len = arg4_struct[1];
    BaseT_arg4 local_arg4(arg4_data, arg4_data + arg4_len);
    ptr->process_other_containers(local_arg0, local_arg1, local_arg2, local_arg3, local_arg4);
    std::vector<ValT_arg0> new_arg0_flat(local_arg0.begin(), local_arg0.end());
    ValT_arg0* new_arg0_data = (ValT_arg0*) cerridwen::plugin::allocate(new_arg0_flat.size() * sizeof(ValT_arg0));
    std::memcpy((void*)new_arg0_data, new_arg0_flat.data(), new_arg0_flat.size() * sizeof(ValT_arg0));
    arg0_struct[0] = reinterpret_cast<uint32_t>(new_arg0_data);
    arg0_struct[1] = new_arg0_flat.size();
    std::vector<ValT_arg1> new_arg1_flat(local_arg1.begin(), local_arg1.end());
    ValT_arg1* new_arg1_data = (ValT_arg1*) cerridwen::plugin::allocate(new_arg1_flat.size() * sizeof(ValT_arg1));
    std::memcpy((void*)new_arg1_data, new_arg1_flat.data(), new_arg1_flat.size() * sizeof(ValT_arg1));
    arg1_struct[0] = reinterpret_cast<uint32_t>(new_arg1_data);
    arg1_struct[1] = new_arg1_flat.size();
    std::vector<ValT_arg2> new_arg2_flat(local_arg2.begin(), local_arg2.end());
    ValT_arg2* new_arg2_data = (ValT_arg2*) cerridwen::plugin::allocate(new_arg2_flat.size() * sizeof(ValT_arg2));
    std::memcpy((void*)new_arg2_data, new_arg2_flat.data(), new_arg2_flat.size() * sizeof(ValT_arg2));
    arg2_struct[0] = reinterpret_cast<uint32_t>(new_arg2_data);
    arg2_struct[1] = new_arg2_flat.size();
    std::vector<ValT_arg3> new_arg3_flat(local_arg3.begin(), local_arg3.end());
    ValT_arg3* new_arg3_data = (ValT_arg3*) cerridwen::plugin::allocate(new_arg3_flat.size() * sizeof(ValT_arg3));
    std::memcpy((void*)new_arg3_data, new_arg3_flat.data(), new_arg3_flat.size() * sizeof(ValT_arg3));
    arg3_struct[0] = reinterpret_cast<uint32_t>(new_arg3_data);
    arg3_struct[1] = new_arg3_flat.size();
    std::vector<PairT_arg4> new_arg4_flat(local_arg4.begin(), local_arg4.end());
    PairT_arg4* new_arg4_data = (PairT_arg4*) cerridwen::plugin::allocate(new_arg4_flat.size() * sizeof(PairT_arg4));
    std::memcpy((void*)new_arg4_data, new_arg4_flat.data(), new_arg4_flat.size() * sizeof(PairT_arg4));
    arg4_struct[0] = reinterpret_cast<uint32_t>(new_arg4_data);
    arg4_struct[1] = new_arg4_flat.size();
}

EMSCRIPTEN_KEEPALIVE void ContainerPlugin_process_generic_refs(ContainerPlugin* ptr, uint32_t arg0_ptr, uint32_t arg1_ptr, uint32_t arg2_ptr) {
    using BaseT_arg0 = std::remove_reference_t<std::variant<int, float>&>;
    BaseT_arg0& local_arg0 = *reinterpret_cast<BaseT_arg0*>(arg0_ptr);
    using BaseT_arg1 = std::remove_reference_t<DummyVisitor&>;
    BaseT_arg1& local_arg1 = *reinterpret_cast<BaseT_arg1*>(arg1_ptr);
    using BaseT_arg2 = std::remove_reference_t<MyFunctor&>;
    BaseT_arg2& local_arg2 = *reinterpret_cast<BaseT_arg2*>(arg2_ptr);
    ptr->process_generic_refs(local_arg0, local_arg1, local_arg2);
}

EMSCRIPTEN_KEEPALIVE void ContainerPlugin_process_shared_ptr(ContainerPlugin* ptr, uint32_t arg0) {
    using BaseT_arg0 = std::remove_reference_t<std::shared_ptr<int>&>;
    using ValT_arg0 = BaseT_arg0::element_type;
    uint32_t* arg0_struct = reinterpret_cast<uint32_t*>(arg0);
    uint32_t arg0_is_null = arg0_struct[0];
    uint32_t arg0_data = arg0_struct[1];
    BaseT_arg0 local_arg0;
    if (!arg0_is_null) {
        local_arg0 = std::make_shared<ValT_arg0>(*reinterpret_cast<ValT_arg0*>(arg0_data));
    }
    ptr->process_shared_ptr(local_arg0);
    arg0_struct[0] = (local_arg0 == nullptr);
    if (local_arg0) {
        ValT_arg0* new_arg0_data = (ValT_arg0*) cerridwen::plugin::allocate(sizeof(ValT_arg0));
        std::memcpy((void*)new_arg0_data, local_arg0.get(), sizeof(ValT_arg0));
        arg0_struct[1] = reinterpret_cast<uint32_t>(new_arg0_data);
    } else {
        arg0_struct[1] = 0;
    }
}

} // extern "C"
