#pragma once
#include "host_classes.hpp"
// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---
extern "C" {
    __attribute__((import_module("env"), import_name("LoggerHost_log_message")))
    void LoggerHost_log_message(uint64_t ptr, const char* arg0);
    __attribute__((import_module("env"), import_name("LoggerHost_get_timestamp")))
    int LoggerHost_get_timestamp(uint64_t ptr);
}

class LoggerHost_Proxy : public LoggerHost {
public:
    uint64_t _host_ptr = 0;
    LoggerHost_Proxy(uint64_t p) : _host_ptr(p) {}

    void log_message(const char* arg0) override {
        LoggerHost_log_message(_host_ptr, arg0);
    }
    int get_timestamp() override {
        return LoggerHost_get_timestamp(_host_ptr);
    }
};
