#pragma once
#include "host_classes.hpp"
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <stdexcept>
#include <cerridwen/plugin_manager.hpp>

class MathPlugin_Trampoline : public MathPlugin {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~MathPlugin_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function
            _wasm_instance->call("MathPlugin_destroy", _wasm_ptr);
        }
    }

    // Inherit constructors
    using MathPlugin::MathPlugin;

    // Marshalled property accessors for: counter
    void sync_counter() {
        // [Value Marshalling] Call WASM getter to retrieve value
        this->counter = _wasm_instance->call_int("MathPlugin_get_counter", _wasm_ptr);
    }
    void increment() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        _wasm_instance->call("MathPlugin_increment", _wasm_ptr);
        sync_counter();
    }

    void decrement() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        _wasm_instance->call("MathPlugin_decrement", _wasm_ptr);
        sync_counter();
    }

    int multiply(int arg0, int arg1) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _args.push_back(std::to_string(arg1));
        auto _ret = _wasm_instance->call_args_int("MathPlugin_multiply", _args);
        sync_counter();
        return _ret;
    }

    void do_logging(long long unsigned int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _wasm_instance->call_args("MathPlugin_do_logging", _args);
        sync_counter();
    }

};
// --- Generated by Cerridwen WebAssembly HOST-EXPORTS Generator ---
#include <wasm3.h>
#include <m3_env.h>

m3ApiRawFunction(LoggerHost_log_message_wrapper) {
    m3ApiGetArg(uint64_t, host_ptr);
    m3ApiGetArgMem(const char*, arg0);
    LoggerHost* obj = reinterpret_cast<LoggerHost*>(static_cast<uintptr_t>(host_ptr));
    printf("[Wasm3] Wrapper called for log_message with host_ptr=%llx (obj=%p)\n", (unsigned long long)host_ptr, (void*)obj);
    try {
        obj->log_message(arg0);
        m3ApiSuccess();
    } catch (const std::exception& e) {
        m3ApiTrap(e.what());
    } catch (...) {
        m3ApiTrap("Unknown C++ exception in host method LoggerHost::log_message");
    }
}

m3ApiRawFunction(LoggerHost_get_timestamp_wrapper) {
    m3ApiReturnType(int);
    m3ApiGetArg(uint64_t, host_ptr);
    LoggerHost* obj = reinterpret_cast<LoggerHost*>(static_cast<uintptr_t>(host_ptr));
    printf("[Wasm3] Wrapper called for get_timestamp with host_ptr=%llx (obj=%p)\n", (unsigned long long)host_ptr, (void*)obj);
    try {
        int ret = obj->get_timestamp();
        m3ApiReturn(ret);
    } catch (const std::exception& e) {
        m3ApiTrap(e.what());
    } catch (...) {
        m3ApiTrap("Unknown C++ exception in host method LoggerHost::get_timestamp");
    }
}

inline void bind_LoggerHost(IM3Module module) {
    {
        M3Result res = m3_LinkRawFunction(module, "env", "LoggerHost_log_message", "v(Ii)", &LoggerHost_log_message_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "LoggerHost_log_message: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "LoggerHost_get_timestamp", "i(I)", &LoggerHost_get_timestamp_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "LoggerHost_get_timestamp: " + res);
    }
}

