#pragma once
#include "host_classes.hpp"
// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---
#include <memory>
extern "C" {
    __attribute__((import_module("env"), import_name("LoggerHost_log_message")))
    void LoggerHost_log_message(uint64_t ptr, const char* arg0);
    __attribute__((import_module("env"), import_name("LoggerHost_get_timestamp")))
    int LoggerHost_get_timestamp(uint64_t ptr);
    __attribute__((import_module("env"), import_name("LoggerHost_shared_release")))
    void LoggerHost_shared_release(uint64_t handle);
    __attribute__((import_module("env"), import_name("LoggerHost_shared_clone")))
    uint64_t LoggerHost_shared_clone(uint64_t handle);
    __attribute__((import_module("env"), import_name("LoggerHost_shared_get_raw")))
    uint64_t LoggerHost_shared_get_raw(uint64_t handle);
}

class LoggerHost_Proxy : public LoggerHost {
public:
    uint64_t _host_ptr = 0;
    LoggerHost_Proxy(uint64_t p = 0) : _host_ptr(p) {}
    // Re-targets this proxy at a (different) host object
    void cerridwen_bind(uint64_t p) { _host_ptr = p; }

    void log_message(const char* arg0) override {
        LoggerHost_log_message(_host_ptr, arg0);
    }
    int get_timestamp() override {
        return LoggerHost_get_timestamp(_host_ptr);
    }
};

class LoggerHost_SharedProxy : public LoggerHost_Proxy {
public:
    uint64_t _shared_handle = 0;
    LoggerHost_SharedProxy(uint64_t handle = 0) : LoggerHost_Proxy(handle ? LoggerHost_shared_get_raw(handle) : 0), _shared_handle(handle) {}
    LoggerHost_SharedProxy(const LoggerHost_SharedProxy& other) : LoggerHost_Proxy(other._host_ptr) {
        if (other._shared_handle) {
            _shared_handle = LoggerHost_shared_clone(other._shared_handle);
        }
    }
    LoggerHost_SharedProxy& operator=(const LoggerHost_SharedProxy& other) {
        if (this != &other) {
            if (_shared_handle) LoggerHost_shared_release(_shared_handle);
            _host_ptr = other._host_ptr;
            _shared_handle = other._shared_handle ? LoggerHost_shared_clone(other._shared_handle) : 0;
        }
        return *this;
    }
    ~LoggerHost_SharedProxy() override {
        if (_shared_handle) {
            LoggerHost_shared_release(_shared_handle);
        }
    }
};
// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---
#include <memory>
extern "C" {
    __attribute__((import_module("env"), import_name("Calculator_add")))
    int Calculator_add(uint64_t ptr, int arg0, int arg1);
    __attribute__((import_module("env"), import_name("Calculator_divide")))
    int Calculator_divide(uint64_t ptr, int arg0, int arg1);
    __attribute__((import_module("env"), import_name("Calculator_shared_release")))
    void Calculator_shared_release(uint64_t handle);
    __attribute__((import_module("env"), import_name("Calculator_shared_clone")))
    uint64_t Calculator_shared_clone(uint64_t handle);
    __attribute__((import_module("env"), import_name("Calculator_shared_get_raw")))
    uint64_t Calculator_shared_get_raw(uint64_t handle);
}

class Calculator_Proxy : public Calculator {
public:
    uint64_t _host_ptr = 0;
    Calculator_Proxy(uint64_t p = 0) : _host_ptr(p) {}
    // Re-targets this proxy at a (different) host object
    void cerridwen_bind(uint64_t p) { _host_ptr = p; }

    int add(int arg0, int arg1) override {
        return Calculator_add(_host_ptr, arg0, arg1);
    }
    int divide(int arg0, int arg1) override {
        return Calculator_divide(_host_ptr, arg0, arg1);
    }
};

class Calculator_SharedProxy : public Calculator_Proxy {
public:
    uint64_t _shared_handle = 0;
    Calculator_SharedProxy(uint64_t handle = 0) : Calculator_Proxy(handle ? Calculator_shared_get_raw(handle) : 0), _shared_handle(handle) {}
    Calculator_SharedProxy(const Calculator_SharedProxy& other) : Calculator_Proxy(other._host_ptr) {
        if (other._shared_handle) {
            _shared_handle = Calculator_shared_clone(other._shared_handle);
        }
    }
    Calculator_SharedProxy& operator=(const Calculator_SharedProxy& other) {
        if (this != &other) {
            if (_shared_handle) Calculator_shared_release(_shared_handle);
            _host_ptr = other._host_ptr;
            _shared_handle = other._shared_handle ? Calculator_shared_clone(other._shared_handle) : 0;
        }
        return *this;
    }
    ~Calculator_SharedProxy() override {
        if (_shared_handle) {
            Calculator_shared_release(_shared_handle);
        }
    }
};
// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---
#include <memory>
extern "C" {
    __attribute__((import_module("env"), import_name("Animal_legs")))
    int Animal_legs(uint64_t ptr);
    __attribute__((import_module("env"), import_name("Animal_sound_id")))
    int Animal_sound_id(uint64_t ptr);
    __attribute__((import_module("env"), import_name("Animal_describe")))
    int Animal_describe(uint64_t ptr);
    __attribute__((import_module("env"), import_name("Animal_shared_release")))
    void Animal_shared_release(uint64_t handle);
    __attribute__((import_module("env"), import_name("Animal_shared_clone")))
    uint64_t Animal_shared_clone(uint64_t handle);
    __attribute__((import_module("env"), import_name("Animal_shared_get_raw")))
    uint64_t Animal_shared_get_raw(uint64_t handle);
}

class Animal_Proxy : public Animal {
public:
    uint64_t _host_ptr = 0;
    Animal_Proxy(uint64_t p = 0) : _host_ptr(p) {}
    // Re-targets this proxy at a (different) host object
    void cerridwen_bind(uint64_t p) { _host_ptr = p; }

    int legs() override {
        return Animal_legs(_host_ptr);
    }
    int sound_id() override {
        return Animal_sound_id(_host_ptr);
    }
    int describe() override {
        return Animal_describe(_host_ptr);
    }
};

class Animal_SharedProxy : public Animal_Proxy {
public:
    uint64_t _shared_handle = 0;
    Animal_SharedProxy(uint64_t handle = 0) : Animal_Proxy(handle ? Animal_shared_get_raw(handle) : 0), _shared_handle(handle) {}
    Animal_SharedProxy(const Animal_SharedProxy& other) : Animal_Proxy(other._host_ptr) {
        if (other._shared_handle) {
            _shared_handle = Animal_shared_clone(other._shared_handle);
        }
    }
    Animal_SharedProxy& operator=(const Animal_SharedProxy& other) {
        if (this != &other) {
            if (_shared_handle) Animal_shared_release(_shared_handle);
            _host_ptr = other._host_ptr;
            _shared_handle = other._shared_handle ? Animal_shared_clone(other._shared_handle) : 0;
        }
        return *this;
    }
    ~Animal_SharedProxy() override {
        if (_shared_handle) {
            Animal_shared_release(_shared_handle);
        }
    }
};
