#pragma once
#include "host_classes.hpp"
// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---
extern "C" {
    __attribute__((import_module("env"), import_name("LoggerHost_log_message")))
    void LoggerHost_log_message(uint64_t ptr, const char* arg0);
    __attribute__((import_module("env"), import_name("LoggerHost_get_timestamp")))
    int LoggerHost_get_timestamp(uint64_t ptr);
}

class LoggerHost_Proxy : public LoggerHost {
public:
    uint64_t _host_ptr = 0;
    LoggerHost_Proxy(uint64_t p = 0) : _host_ptr(p) {}
    // Re-targets this proxy at a (different) host object
    void cerridwen_bind(uint64_t p) { _host_ptr = p; }

    void log_message(const char* arg0) override {
        LoggerHost_log_message(_host_ptr, arg0);
    }
    int get_timestamp() override {
        return LoggerHost_get_timestamp(_host_ptr);
    }
};
// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---
extern "C" {
    __attribute__((import_module("env"), import_name("Calculator_add")))
    int Calculator_add(uint64_t ptr, int arg0, int arg1);
    __attribute__((import_module("env"), import_name("Calculator_divide")))
    int Calculator_divide(uint64_t ptr, int arg0, int arg1);
}

class Calculator_Proxy : public Calculator {
public:
    uint64_t _host_ptr = 0;
    Calculator_Proxy(uint64_t p = 0) : _host_ptr(p) {}
    // Re-targets this proxy at a (different) host object
    void cerridwen_bind(uint64_t p) { _host_ptr = p; }

    int add(int arg0, int arg1) override {
        return Calculator_add(_host_ptr, arg0, arg1);
    }
    int divide(int arg0, int arg1) override {
        return Calculator_divide(_host_ptr, arg0, arg1);
    }
};
// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---
extern "C" {
    __attribute__((import_module("env"), import_name("Animal_legs")))
    int Animal_legs(uint64_t ptr);
    __attribute__((import_module("env"), import_name("Animal_sound_id")))
    int Animal_sound_id(uint64_t ptr);
    __attribute__((import_module("env"), import_name("Animal_describe")))
    int Animal_describe(uint64_t ptr);
}

class Animal_Proxy : public Animal {
public:
    uint64_t _host_ptr = 0;
    Animal_Proxy(uint64_t p = 0) : _host_ptr(p) {}
    // Re-targets this proxy at a (different) host object
    void cerridwen_bind(uint64_t p) { _host_ptr = p; }

    int legs() override {
        return Animal_legs(_host_ptr);
    }
    int sound_id() override {
        return Animal_sound_id(_host_ptr);
    }
    int describe() override {
        return Animal_describe(_host_ptr);
    }
};
