#include "plugin.hpp"
#include "host_classes.hpp"
// --- Generated by Cerridwen WebAssembly EXPORT Generator ---
#include <emscripten.h>

extern "C" {

EMSCRIPTEN_KEEPALIVE MathPlugin* MathPlugin_create() {
    return new MathPlugin();
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_destroy(MathPlugin* ptr) {
    delete ptr;
}

EMSCRIPTEN_KEEPALIVE int MathPlugin_get_counter(MathPlugin* ptr) {
    return ptr->counter;
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_set_counter(MathPlugin* ptr, int val) {
    ptr->counter = val;
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_increment(MathPlugin* ptr) {
    ptr->increment();
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_decrement(MathPlugin* ptr) {
    ptr->decrement();
}

EMSCRIPTEN_KEEPALIVE int MathPlugin_multiply(MathPlugin* ptr, int arg0, int arg1) {
    return ptr->multiply(arg0, arg1);
}

EMSCRIPTEN_KEEPALIVE void MathPlugin_do_logging(MathPlugin* ptr, long long unsigned int arg0) {
    ptr->do_logging(arg0);
}

} // extern "C"
