#pragma once
#include "host_classes.hpp"
#include "plugin.hpp"
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class MathPlugin_Trampoline : public MathPlugin {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    // Thread Safe Plugin Locking
    std::mutex _plugin_mutex;

    ~MathPlugin_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("MathPlugin_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using MathPlugin::MathPlugin;

    // Marshalled property accessors for: counter
    void sync_counter() {
        // [Value Marshalling] Call WASM getter to retrieve value
        this->counter = _wasm_instance->call_int("MathPlugin_get_counter", _wasm_ptr);
    }
    void increment() override {
        std::lock_guard<std::mutex> lock(_plugin_mutex);
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        _wasm_instance->call("MathPlugin_increment", _wasm_ptr);
        sync_counter();
    }

    void decrement() override {
        std::lock_guard<std::mutex> lock(_plugin_mutex);
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        _wasm_instance->call("MathPlugin_decrement", _wasm_ptr);
        sync_counter();
    }

    int multiply(int arg0, int arg1) override {
        std::lock_guard<std::mutex> lock(_plugin_mutex);
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _args.push_back(std::to_string(arg1));
        auto _ret = _wasm_instance->call_args_int("MathPlugin_multiply", _args);
        sync_counter();
        return _ret;
    }

    void do_logging(long long unsigned int arg0) override {
        std::lock_guard<std::mutex> lock(_plugin_mutex);
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("MathPlugin_set_counter", _wasm_ptr, this->counter);
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _wasm_instance->call_args("MathPlugin_do_logging", _args);
        sync_counter();
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Shape_Trampoline : public Shape {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Shape_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Shape_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Shape::Shape;

    int sides() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Shape_sides", _wasm_ptr);
        return _ret;
    }

    int area() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Shape_area", _wasm_ptr);
        return _ret;
    }

    int describe() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Shape_describe", _wasm_ptr);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Rect_Trampoline : public Rect {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Rect_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Rect_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Rect::Rect;

    // Marshalled property accessors for: w
    void sync_w() {
        // [Value Marshalling] Call WASM getter to retrieve value
        this->w = _wasm_instance->call_int("Rect_get_w", _wasm_ptr);
    }
    // Marshalled property accessors for: h
    void sync_h() {
        // [Value Marshalling] Call WASM getter to retrieve value
        this->h = _wasm_instance->call_int("Rect_get_h", _wasm_ptr);
    }
    int sides() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("Rect_set_w", _wasm_ptr, this->w);
        _wasm_instance->call_set_int("Rect_set_h", _wasm_ptr, this->h);
        auto _ret = _wasm_instance->call_int("Rect_sides", _wasm_ptr);
        sync_w();
        sync_h();
        return _ret;
    }

    int area() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("Rect_set_w", _wasm_ptr, this->w);
        _wasm_instance->call_set_int("Rect_set_h", _wasm_ptr, this->h);
        auto _ret = _wasm_instance->call_int("Rect_area", _wasm_ptr);
        sync_w();
        sync_h();
        return _ret;
    }

    int describe() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("Rect_set_w", _wasm_ptr, this->w);
        _wasm_instance->call_set_int("Rect_set_h", _wasm_ptr, this->h);
        auto _ret = _wasm_instance->call_int("Rect_describe", _wasm_ptr);
        sync_w();
        sync_h();
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Square_Trampoline : public Square {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Square_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Square_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Square::Square;

    // Marshalled property accessors for: w
    void sync_w() {
        // [Value Marshalling] Call WASM getter to retrieve value
        this->w = _wasm_instance->call_int("Square_get_w", _wasm_ptr);
    }
    // Marshalled property accessors for: h
    void sync_h() {
        // [Value Marshalling] Call WASM getter to retrieve value
        this->h = _wasm_instance->call_int("Square_get_h", _wasm_ptr);
    }
    int describe() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("Square_set_w", _wasm_ptr, this->w);
        _wasm_instance->call_set_int("Square_set_h", _wasm_ptr, this->h);
        auto _ret = _wasm_instance->call_int("Square_describe", _wasm_ptr);
        sync_w();
        sync_h();
        return _ret;
    }

    int sides() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("Square_set_w", _wasm_ptr, this->w);
        _wasm_instance->call_set_int("Square_set_h", _wasm_ptr, this->h);
        auto _ret = _wasm_instance->call_int("Square_sides", _wasm_ptr);
        sync_w();
        sync_h();
        return _ret;
    }

    int area() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call_set_int("Square_set_w", _wasm_ptr, this->w);
        _wasm_instance->call_set_int("Square_set_h", _wasm_ptr, this->h);
        auto _ret = _wasm_instance->call_int("Square_area", _wasm_ptr);
        sync_w();
        sync_h();
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Walker_Trampoline : public Walker {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Walker_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Walker_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Walker::Walker;

    int walk(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("Walker_walk", _args);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Swimmer_Trampoline : public Swimmer {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Swimmer_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Swimmer_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Swimmer::Swimmer;

    int swim(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("Swimmer_swim", _args);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Duck_Trampoline : public Duck {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Duck_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Duck_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Duck::Duck;

    int walk(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("Duck_walk", _args);
        return _ret;
    }

    int swim(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("Duck_swim", _args);
        return _ret;
    }

    int fly() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Duck_fly", _wasm_ptr);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Entity_Trampoline : public Entity {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Entity_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Entity_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Entity::Entity;

    int id() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Entity_id", _wasm_ptr);
        return _ret;
    }

    int kind() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Entity_kind", _wasm_ptr);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Named_Trampoline : public Named {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Named_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Named_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Named::Named;

    int kind() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Named_kind", _wasm_ptr);
        return _ret;
    }

    int name_len() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Named_name_len", _wasm_ptr);
        return _ret;
    }

    int id() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Named_id", _wasm_ptr);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Tagged_Trampoline : public Tagged {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Tagged_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Tagged_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Tagged::Tagged;

    int id() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Tagged_id", _wasm_ptr);
        return _ret;
    }

    int tag_count() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Tagged_tag_count", _wasm_ptr);
        return _ret;
    }

    int kind() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Tagged_kind", _wasm_ptr);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Widget_Trampoline : public Widget {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Widget_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Widget_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Widget::Widget;

    int total() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Widget_total", _wasm_ptr);
        return _ret;
    }

    int kind() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Widget_kind", _wasm_ptr);
        return _ret;
    }

    int name_len() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Widget_name_len", _wasm_ptr);
        return _ret;
    }

    int id() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Widget_id", _wasm_ptr);
        return _ret;
    }

    int tag_count() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Widget_tag_count", _wasm_ptr);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Bird_Trampoline : public Bird {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Bird_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Bird_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Bird::Bird;

    int legs() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Bird_legs", _wasm_ptr);
        return _ret;
    }

    int sound_id() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Bird_sound_id", _wasm_ptr);
        return _ret;
    }

    int describe() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("Bird_describe", _wasm_ptr);
        return _ret;
    }

    void attach(long long unsigned int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _wasm_instance->call_args("Bird_attach", _args);
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class Thrower_Trampoline : public Thrower {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~Thrower_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("Thrower_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using Thrower::Thrower;

    int risky(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("Thrower_risky", _args);
        return _ret;
    }

    int divide_via_host(long long unsigned int arg0, int arg1, int arg2) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _args.push_back(std::to_string(arg1));
        _args.push_back(std::to_string(arg2));
        auto _ret = _wasm_instance->call_args_int("Thrower_divide_via_host", _args);
        return _ret;
    }

    int add_via_host(long long unsigned int arg0, int arg1, int arg2) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _args.push_back(std::to_string(arg1));
        _args.push_back(std::to_string(arg2));
        auto _ret = _wasm_instance->call_args_int("Thrower_add_via_host", _args);
        return _ret;
    }

    int divide_via_shared_host(long long unsigned int arg0, int arg1, int arg2) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _args.push_back(std::to_string(arg1));
        _args.push_back(std::to_string(arg2));
        auto _ret = _wasm_instance->call_args_int("Thrower_divide_via_shared_host", _args);
        return _ret;
    }

    void crash() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        _wasm_instance->call("Thrower_crash", _wasm_ptr);
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class MemoryProbe_Trampoline : public MemoryProbe {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~MemoryProbe_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("MemoryProbe_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using MemoryProbe::MemoryProbe;

    int alloc_block(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("MemoryProbe_alloc_block", _args);
        return _ret;
    }

    int free_all() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("MemoryProbe_free_all", _wasm_ptr);
        return _ret;
    }

    int block_count() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("MemoryProbe_block_count", _wasm_ptr);
        return _ret;
    }

    int pages() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("MemoryProbe_pages", _wasm_ptr);
        return _ret;
    }

    int grow(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("MemoryProbe_grow", _args);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---
#include <functional>
#include <mutex>
#include <stdexcept>
#include <cerridwen/errors.hpp>
#include <cerridwen/plugin_manager.hpp>

class StorageClient_Trampoline : public StorageClient {
public:
    cerridwen::WasmInstance* _wasm_instance = nullptr;
    uint32_t _wasm_ptr = 0;

    ~StorageClient_Trampoline() override {
        if (_wasm_instance && _wasm_ptr) {
            // Call WASM destroy function; a destructor must never throw
            try { _wasm_instance->call("StorageClient_destroy", _wasm_ptr); } catch (...) {}
        }
    }

    // Inherit constructors
    using StorageClient::StorageClient;

    int save_number(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("StorageClient_save_number", _args);
        return _ret;
    }

    int load_number() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("StorageClient_load_number", _wasm_ptr);
        return _ret;
    }

    int write_blob(int arg0) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        auto _ret = _wasm_instance->call_args_int("StorageClient_write_blob", _args);
        return _ret;
    }

    int blob_checksum() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("StorageClient_blob_checksum", _wasm_ptr);
        return _ret;
    }

    int try_write(int arg0, int arg1) override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        std::vector<std::string> _args;
        _args.push_back(std::to_string(_wasm_ptr));
        _args.push_back(std::to_string(arg0));
        _args.push_back(std::to_string(arg1));
        auto _ret = _wasm_instance->call_args_int("StorageClient_try_write", _args);
        return _ret;
    }

    int remove_blob() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("StorageClient_remove_blob", _wasm_ptr);
        return _ret;
    }

    int used_bytes() override {
        if (!_wasm_instance) throw std::runtime_error("No WASM instance");
        // Sync data before call
        auto _ret = _wasm_instance->call_int("StorageClient_used_bytes", _wasm_ptr);
        return _ret;
    }

};
// --- Generated by Cerridwen WebAssembly HOST-EXPORTS Generator ---
#include <wasm3.h>
#include <m3_env.h>
#include <memory>

[[maybe_unused]] static m3ApiRawFunction(LoggerHost_log_message_wrapper) {
    m3ApiGetArg(uint64_t, host_ptr);
    m3ApiGetArgMem(const char*, arg0);
    LoggerHost* obj = reinterpret_cast<LoggerHost*>(static_cast<uintptr_t>(host_ptr));
    try {
        obj->log_message(arg0);
        m3ApiSuccess();
    } catch (const cerridwen::PluginException& e) {
        cerridwen::record_plugin_error(e.what());
        m3ApiTrap("cerridwen:plugin_exception");
    } catch (const std::exception& e) {
        cerridwen::record_host_error(e.what());
        m3ApiTrap("cerridwen:host_exception");
    } catch (...) {
        cerridwen::record_host_error("Unknown C++ exception in host method LoggerHost::log_message");
        m3ApiTrap("cerridwen:host_exception");
    }
}

[[maybe_unused]] static m3ApiRawFunction(LoggerHost_get_timestamp_wrapper) {
    m3ApiReturnType(int);
    m3ApiGetArg(uint64_t, host_ptr);
    LoggerHost* obj = reinterpret_cast<LoggerHost*>(static_cast<uintptr_t>(host_ptr));
    try {
        int ret = obj->get_timestamp();
        m3ApiReturn(ret);
    } catch (const cerridwen::PluginException& e) {
        cerridwen::record_plugin_error(e.what());
        m3ApiTrap("cerridwen:plugin_exception");
    } catch (const std::exception& e) {
        cerridwen::record_host_error(e.what());
        m3ApiTrap("cerridwen:host_exception");
    } catch (...) {
        cerridwen::record_host_error("Unknown C++ exception in host method LoggerHost::get_timestamp");
        m3ApiTrap("cerridwen:host_exception");
    }
}

[[maybe_unused]] static m3ApiRawFunction(LoggerHost_shared_release) {
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<LoggerHost>*>(static_cast<uintptr_t>(handle));
    delete sptr;
    m3ApiSuccess();
}

[[maybe_unused]] static m3ApiRawFunction(LoggerHost_shared_clone) {
    m3ApiReturnType(uint64_t);
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<LoggerHost>*>(static_cast<uintptr_t>(handle));
    auto* new_sptr = new std::shared_ptr<LoggerHost>(*sptr);
    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(new_sptr)));
}

[[maybe_unused]] static m3ApiRawFunction(LoggerHost_shared_get_raw) {
    m3ApiReturnType(uint64_t);
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<LoggerHost>*>(static_cast<uintptr_t>(handle));
    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(sptr->get())));
}

inline void bind_LoggerHost(IM3Module module) {
    {
        M3Result res = m3_LinkRawFunction(module, "env", "LoggerHost_log_message", "v(Ii)", &LoggerHost_log_message_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "LoggerHost_log_message: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "LoggerHost_get_timestamp", "i(I)", &LoggerHost_get_timestamp_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "LoggerHost_get_timestamp: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "LoggerHost_shared_release", "v(I)", &LoggerHost_shared_release);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "LoggerHost_shared_release: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "LoggerHost_shared_clone", "I(I)", &LoggerHost_shared_clone);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "LoggerHost_shared_clone: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "LoggerHost_shared_get_raw", "I(I)", &LoggerHost_shared_get_raw);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "LoggerHost_shared_get_raw: " + res);
    }
}

// --- Generated by Cerridwen WebAssembly HOST-EXPORTS Generator ---
#include <wasm3.h>
#include <m3_env.h>
#include <memory>

[[maybe_unused]] static m3ApiRawFunction(Calculator_add_wrapper) {
    m3ApiReturnType(int);
    m3ApiGetArg(uint64_t, host_ptr);
    m3ApiGetArg(int, arg0);
    m3ApiGetArg(int, arg1);
    Calculator* obj = reinterpret_cast<Calculator*>(static_cast<uintptr_t>(host_ptr));
    try {
        int ret = obj->add(arg0, arg1);
        m3ApiReturn(ret);
    } catch (const cerridwen::PluginException& e) {
        cerridwen::record_plugin_error(e.what());
        m3ApiTrap("cerridwen:plugin_exception");
    } catch (const std::exception& e) {
        cerridwen::record_host_error(e.what());
        m3ApiTrap("cerridwen:host_exception");
    } catch (...) {
        cerridwen::record_host_error("Unknown C++ exception in host method Calculator::add");
        m3ApiTrap("cerridwen:host_exception");
    }
}

[[maybe_unused]] static m3ApiRawFunction(Calculator_divide_wrapper) {
    m3ApiReturnType(int);
    m3ApiGetArg(uint64_t, host_ptr);
    m3ApiGetArg(int, arg0);
    m3ApiGetArg(int, arg1);
    Calculator* obj = reinterpret_cast<Calculator*>(static_cast<uintptr_t>(host_ptr));
    try {
        int ret = obj->divide(arg0, arg1);
        m3ApiReturn(ret);
    } catch (const cerridwen::PluginException& e) {
        cerridwen::record_plugin_error(e.what());
        m3ApiTrap("cerridwen:plugin_exception");
    } catch (const std::exception& e) {
        cerridwen::record_host_error(e.what());
        m3ApiTrap("cerridwen:host_exception");
    } catch (...) {
        cerridwen::record_host_error("Unknown C++ exception in host method Calculator::divide");
        m3ApiTrap("cerridwen:host_exception");
    }
}

[[maybe_unused]] static m3ApiRawFunction(Calculator_shared_release) {
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<Calculator>*>(static_cast<uintptr_t>(handle));
    delete sptr;
    m3ApiSuccess();
}

[[maybe_unused]] static m3ApiRawFunction(Calculator_shared_clone) {
    m3ApiReturnType(uint64_t);
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<Calculator>*>(static_cast<uintptr_t>(handle));
    auto* new_sptr = new std::shared_ptr<Calculator>(*sptr);
    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(new_sptr)));
}

[[maybe_unused]] static m3ApiRawFunction(Calculator_shared_get_raw) {
    m3ApiReturnType(uint64_t);
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<Calculator>*>(static_cast<uintptr_t>(handle));
    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(sptr->get())));
}

inline void bind_Calculator(IM3Module module) {
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Calculator_add", "i(Iii)", &Calculator_add_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Calculator_add: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Calculator_divide", "i(Iii)", &Calculator_divide_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Calculator_divide: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Calculator_shared_release", "v(I)", &Calculator_shared_release);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Calculator_shared_release: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Calculator_shared_clone", "I(I)", &Calculator_shared_clone);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Calculator_shared_clone: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Calculator_shared_get_raw", "I(I)", &Calculator_shared_get_raw);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Calculator_shared_get_raw: " + res);
    }
}

// --- Generated by Cerridwen WebAssembly HOST-EXPORTS Generator ---
#include <wasm3.h>
#include <m3_env.h>
#include <memory>

[[maybe_unused]] static m3ApiRawFunction(Animal_legs_wrapper) {
    m3ApiReturnType(int);
    m3ApiGetArg(uint64_t, host_ptr);
    Animal* obj = reinterpret_cast<Animal*>(static_cast<uintptr_t>(host_ptr));
    try {
        int ret = obj->legs();
        m3ApiReturn(ret);
    } catch (const cerridwen::PluginException& e) {
        cerridwen::record_plugin_error(e.what());
        m3ApiTrap("cerridwen:plugin_exception");
    } catch (const std::exception& e) {
        cerridwen::record_host_error(e.what());
        m3ApiTrap("cerridwen:host_exception");
    } catch (...) {
        cerridwen::record_host_error("Unknown C++ exception in host method Animal::legs");
        m3ApiTrap("cerridwen:host_exception");
    }
}

[[maybe_unused]] static m3ApiRawFunction(Animal_sound_id_wrapper) {
    m3ApiReturnType(int);
    m3ApiGetArg(uint64_t, host_ptr);
    Animal* obj = reinterpret_cast<Animal*>(static_cast<uintptr_t>(host_ptr));
    try {
        int ret = obj->sound_id();
        m3ApiReturn(ret);
    } catch (const cerridwen::PluginException& e) {
        cerridwen::record_plugin_error(e.what());
        m3ApiTrap("cerridwen:plugin_exception");
    } catch (const std::exception& e) {
        cerridwen::record_host_error(e.what());
        m3ApiTrap("cerridwen:host_exception");
    } catch (...) {
        cerridwen::record_host_error("Unknown C++ exception in host method Animal::sound_id");
        m3ApiTrap("cerridwen:host_exception");
    }
}

[[maybe_unused]] static m3ApiRawFunction(Animal_describe_wrapper) {
    m3ApiReturnType(int);
    m3ApiGetArg(uint64_t, host_ptr);
    Animal* obj = reinterpret_cast<Animal*>(static_cast<uintptr_t>(host_ptr));
    try {
        int ret = obj->describe();
        m3ApiReturn(ret);
    } catch (const cerridwen::PluginException& e) {
        cerridwen::record_plugin_error(e.what());
        m3ApiTrap("cerridwen:plugin_exception");
    } catch (const std::exception& e) {
        cerridwen::record_host_error(e.what());
        m3ApiTrap("cerridwen:host_exception");
    } catch (...) {
        cerridwen::record_host_error("Unknown C++ exception in host method Animal::describe");
        m3ApiTrap("cerridwen:host_exception");
    }
}

[[maybe_unused]] static m3ApiRawFunction(Animal_shared_release) {
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<Animal>*>(static_cast<uintptr_t>(handle));
    delete sptr;
    m3ApiSuccess();
}

[[maybe_unused]] static m3ApiRawFunction(Animal_shared_clone) {
    m3ApiReturnType(uint64_t);
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<Animal>*>(static_cast<uintptr_t>(handle));
    auto* new_sptr = new std::shared_ptr<Animal>(*sptr);
    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(new_sptr)));
}

[[maybe_unused]] static m3ApiRawFunction(Animal_shared_get_raw) {
    m3ApiReturnType(uint64_t);
    m3ApiGetArg(uint64_t, handle);
    auto* sptr = reinterpret_cast<std::shared_ptr<Animal>*>(static_cast<uintptr_t>(handle));
    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(sptr->get())));
}

inline void bind_Animal(IM3Module module) {
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Animal_legs", "i(I)", &Animal_legs_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Animal_legs: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Animal_sound_id", "i(I)", &Animal_sound_id_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Animal_sound_id: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Animal_describe", "i(I)", &Animal_describe_wrapper);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Animal_describe: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Animal_shared_release", "v(I)", &Animal_shared_release);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Animal_shared_release: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Animal_shared_clone", "I(I)", &Animal_shared_clone);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Animal_shared_clone: " + res);
    }
    {
        M3Result res = m3_LinkRawFunction(module, "env", "Animal_shared_get_raw", "I(I)", &Animal_shared_get_raw);
        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string("m3_LinkRawFunction failed for ") + "Animal_shared_get_raw: " + res);
    }
}

