#pragma once

#include <cerridwen/annotations.hpp>
#include <cerridwen/exporter.hpp>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>
#include <meta>

namespace cerridwen {

namespace meta_impl {

struct MethodMeta {
    std::string name;
    std::string return_type;
    bool is_virtual;
    bool is_const;
    std::vector<std::string> param_types;
};

// Extracts name of a type robustly
consteval std::string_view get_type_name(std::meta::info type_info) {
    if (std::meta::has_identifier(type_info)) {
        return std::meta::identifier_of(type_info);
    }
    return std::meta::display_string_of(type_info);
}

consteval std::vector<std::meta::info> get_all_virtual_functions(std::meta::info t) {
    std::vector<std::meta::info> res;
    for (auto mem : std::meta::members_of(t, std::meta::access_context::unchecked())) {
        if (std::meta::is_function(mem) && std::meta::is_virtual(mem) && !std::meta::is_constructor(mem) && !std::meta::is_destructor(mem)) {
            res.push_back(mem);
        }
    }
    for (auto base : std::meta::bases_of(t, std::meta::access_context::unchecked())) {
        auto base_funcs = get_all_virtual_functions(std::meta::type_of(base));
        res.insert(res.end(), base_funcs.begin(), base_funcs.end());
    }
    return res;
}

// Data members that opted into marshalling (marshal_by_value / marshal_by_ref).
// Unannotated members are private plugin state and never cross the boundary.
consteval std::vector<std::meta::info> get_marshalled_members(std::meta::info t) {
    std::vector<std::meta::info> res;
    for (auto m : std::meta::nonstatic_data_members_of(t, std::meta::access_context::unchecked())) {
        if (std::meta::has_identifier(m) &&
            (member_has_annotation<cerridwen::marshal_by_value>(m) || member_has_annotation<cerridwen::marshal_by_ref>(m))) {
            res.push_back(m);
        }
    }
    for (auto base : std::meta::bases_of(t, std::meta::access_context::unchecked())) {
        auto base_members = get_marshalled_members(std::meta::type_of(base));
        res.insert(res.end(), base_members.begin(), base_members.end());
    }
    return res;
}

template<typename T>
void generate_wasm_trampoline(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---\n";
    out << "#include <functional>\n";
    out << "#include <mutex>\n";
    out << "#include <stdexcept>\n";
    out << "#include <cerridwen/errors.hpp>\n";
    out << "#include <cerridwen/plugin_manager.hpp>\n\n";
    out << "class " << class_name << "_Trampoline : public " << class_name << " {\n";
    out << "public:\n";
    out << "    cerridwen::WasmInstance* _wasm_instance = nullptr;\n";
    out << "    uint32_t _wasm_ptr = 0;\n\n";
    
    // Check for thread-safety annotation
    constexpr bool is_thread_safe = member_has_annotation<cerridwen::thread_safe>(type_info);
    if (is_thread_safe) {
        out << "    // Thread Safe Plugin Locking\n";
        out << "    std::mutex _plugin_mutex;\n\n";
    }

    out << "    ~" << class_name << "_Trampoline() override {\n";
    out << "        if (_wasm_instance && _wasm_ptr) {\n";
    out << "            // Call WASM destroy function; a destructor must never throw\n";
    out << "            try { _wasm_instance->call(\"" << class_name << "_destroy\", _wasm_ptr); } catch (...) {}\n";
    out << "        }\n";
    out << "    }\n\n";
    
    out << "    // Inherit constructors\n";
    out << "    using " << class_name << "::" << class_name << ";\n\n";
    
    // Data Marshalling
    constexpr static const auto data_members = std::define_static_array(get_marshalled_members(type_info));
    template for (constexpr auto mem : data_members) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            out << "    // Marshalled property accessors for: " << name << "\n";
            out << "    void sync_" << name << "() {\n";
            if constexpr (member_has_annotation<cerridwen::marshal_by_ref>(mem)) {
                out << "        // [Ref Marshalling] Copy memory directly from WASM linear memory offset\n";
                out << "        // this->" << name << " = _wasm_instance->read_memory( ... );\n";
            } else {
                out << "        // [Value Marshalling] Call WASM getter to retrieve value\n";
                out << "        this->" << name << " = _wasm_instance->call_int(\"" << class_name << "_get_" << name << "\", _wasm_ptr);\n";
            }
            out << "    }\n";
        }
    }

    // Virtual Methods (recursive)
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    std::string param_list_decl = "";
                    std::vector<std::string> param_names;
                    std::vector<std::string> param_types;
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        if (p_idx > 0) param_list_decl += ", ";
                        std::string arg_name = "arg" + std::to_string(p_idx);
                        param_list_decl += p_type + " " + arg_name;
                        param_names.push_back(arg_name);
                        param_types.push_back(p_type);
                        p_idx++;
                    }

                    out << "    " << return_type_str << " " << name << "(" << param_list_decl << ") override {\n";
                    if (is_thread_safe) {
                        out << "        std::lock_guard<std::mutex> lock(_plugin_mutex);\n";
                    }
                    out << "        if (!_wasm_instance) throw std::runtime_error(\"No WASM instance\");\n";
                    out << "        // Sync data before call\n";
                    template for (constexpr auto m2 : data_members) {
                        if constexpr (std::meta::has_identifier(m2)) {
                            std::string_view m2_name = std::meta::identifier_of(m2);
                            if constexpr (!member_has_annotation<cerridwen::marshal_by_ref>(m2)) {
                                out << "        _wasm_instance->call_set_int(\"" << class_name << "_set_" << m2_name << "\", _wasm_ptr, this->" << m2_name << ");\n";
                            }
                        }
                    }
                    
                    std::string serialize_pre_call = "";
                    std::string serialize_post_call = "";
                    
                    if (p_idx > 0) {
                        out << "        std::vector<std::string> _args;\n";
                        out << "        _args.push_back(std::to_string(_wasm_ptr));\n";
                        for (size_t i = 0; i < param_names.size(); i++) {
                            std::string arg_name = param_names[i];
                            std::string p_type = param_types[i];
                            if (p_type.find("std::vector") != std::string::npos && p_type.find("&") != std::string::npos) {
                                serialize_pre_call += 
                                    "        using ValT_" + arg_name + " = std::remove_reference_t<decltype(" + arg_name + ")>::value_type;\n"
                                    "        uint32_t " + arg_name + "_struct = _wasm_instance->allocate(8);\n"
                                    "        uint32_t " + arg_name + "_data = _wasm_instance->allocate(" + arg_name + ".size() * sizeof(ValT_" + arg_name + "));\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_data, " + arg_name + ".data(), " + arg_name + ".size() * sizeof(ValT_" + arg_name + "));\n"
                                    "        uint32_t " + arg_name + "_len = " + arg_name + ".size();\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct, &" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct + 4, &" + arg_name + "_len, 4);\n"
                                    "        _args.push_back(std::to_string(" + arg_name + "_struct));\n";

                                serialize_post_call +=
                                    "        uint32_t new_" + arg_name + "_data = 0;\n"
                                    "        uint32_t new_" + arg_name + "_len = 0;\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct, &new_" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct + 4, &new_" + arg_name + "_len, 4);\n"
                                    "        " + arg_name + ".resize(new_" + arg_name + "_len);\n"
                                    "        _wasm_instance->read_memory(new_" + arg_name + "_data, " + arg_name + ".data(), new_" + arg_name + "_len * sizeof(ValT_" + arg_name + "));\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_struct);\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_data);\n"
                                    "        if (new_" + arg_name + "_data != " + arg_name + "_data) _wasm_instance->deallocate(new_" + arg_name + "_data);\n";
                            } else if ((p_type.find("std::map") != std::string::npos || p_type.find("std::unordered_map") != std::string::npos) && p_type.find("&") != std::string::npos) {
                                serialize_pre_call += 
                                    "        using K_" + arg_name + " = std::remove_reference_t<decltype(" + arg_name + ")>::key_type;\n"
                                    "        using V_" + arg_name + " = std::remove_reference_t<decltype(" + arg_name + ")>::mapped_type;\n"
                                    "        using PairT_" + arg_name + " = std::pair<K_" + arg_name + ", V_" + arg_name + ">;\n"
                                    "        std::vector<PairT_" + arg_name + "> " + arg_name + "_flat(" + arg_name + ".begin(), " + arg_name + ".end());\n"
                                    "        uint32_t " + arg_name + "_struct = _wasm_instance->allocate(8);\n"
                                    "        uint32_t " + arg_name + "_data = _wasm_instance->allocate(" + arg_name + "_flat.size() * sizeof(PairT_" + arg_name + "));\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_data, " + arg_name + "_flat.data(), " + arg_name + "_flat.size() * sizeof(PairT_" + arg_name + "));\n"
                                    "        uint32_t " + arg_name + "_len = " + arg_name + "_flat.size();\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct, &" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct + 4, &" + arg_name + "_len, 4);\n"
                                    "        _args.push_back(std::to_string(" + arg_name + "_struct));\n";

                                serialize_post_call +=
                                    "        uint32_t new_" + arg_name + "_data = 0;\n"
                                    "        uint32_t new_" + arg_name + "_len = 0;\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct, &new_" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct + 4, &new_" + arg_name + "_len, 4);\n"
                                    "        std::vector<PairT_" + arg_name + "> new_" + arg_name + "_flat(new_" + arg_name + "_len);\n"
                                    "        _wasm_instance->read_memory(new_" + arg_name + "_data, new_" + arg_name + "_flat.data(), new_" + arg_name + "_len * sizeof(PairT_" + arg_name + "));\n"
                                    "        " + arg_name + ".clear();\n"
                                    "        " + arg_name + ".insert(new_" + arg_name + "_flat.begin(), new_" + arg_name + "_flat.end());\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_struct);\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_data);\n"
                                    "        if (new_" + arg_name + "_data != " + arg_name + "_data) _wasm_instance->deallocate(new_" + arg_name + "_data);\n";
                            } else if ((p_type.find("list") != std::string::npos || p_type.find("deque") != std::string::npos) && p_type.find("&") != std::string::npos && p_type.find("std::") != std::string::npos) {
                                serialize_pre_call += 
                                    "        using ValT_" + arg_name + " = std::remove_reference_t<decltype(" + arg_name + ")>::value_type;\n"
                                    "        std::vector<ValT_" + arg_name + "> " + arg_name + "_flat(" + arg_name + ".begin(), " + arg_name + ".end());\n"
                                    "        uint32_t " + arg_name + "_struct = _wasm_instance->allocate(8);\n"
                                    "        uint32_t " + arg_name + "_data = _wasm_instance->allocate(" + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_data, " + arg_name + "_flat.data(), " + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                    "        uint32_t " + arg_name + "_len = " + arg_name + "_flat.size();\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct, &" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct + 4, &" + arg_name + "_len, 4);\n"
                                    "        _args.push_back(std::to_string(" + arg_name + "_struct));\n";

                                serialize_post_call +=
                                    "        uint32_t new_" + arg_name + "_data = 0;\n"
                                    "        uint32_t new_" + arg_name + "_len = 0;\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct, &new_" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct + 4, &new_" + arg_name + "_len, 4);\n"
                                    "        std::vector<ValT_" + arg_name + "> new_" + arg_name + "_flat(new_" + arg_name + "_len);\n"
                                    "        _wasm_instance->read_memory(new_" + arg_name + "_data, new_" + arg_name + "_flat.data(), new_" + arg_name + "_len * sizeof(ValT_" + arg_name + "));\n"
                                    "        " + arg_name + ".assign(new_" + arg_name + "_flat.begin(), new_" + arg_name + "_flat.end());\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_struct);\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_data);\n"
                                    "        if (new_" + arg_name + "_data != " + arg_name + "_data) _wasm_instance->deallocate(new_" + arg_name + "_data);\n";
                            } else if ((p_type.find("set") != std::string::npos || p_type.find("unordered_set") != std::string::npos) && p_type.find("&") != std::string::npos && p_type.find("std::") != std::string::npos) {
                                serialize_pre_call += 
                                    "        using ValT_" + arg_name + " = std::remove_reference_t<decltype(" + arg_name + ")>::value_type;\n"
                                    "        std::vector<ValT_" + arg_name + "> " + arg_name + "_flat(" + arg_name + ".begin(), " + arg_name + ".end());\n"
                                    "        uint32_t " + arg_name + "_struct = _wasm_instance->allocate(8);\n"
                                    "        uint32_t " + arg_name + "_data = _wasm_instance->allocate(" + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_data, " + arg_name + "_flat.data(), " + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                    "        uint32_t " + arg_name + "_len = " + arg_name + "_flat.size();\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct, &" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->write_memory(" + arg_name + "_struct + 4, &" + arg_name + "_len, 4);\n"
                                    "        _args.push_back(std::to_string(" + arg_name + "_struct));\n";

                                serialize_post_call +=
                                    "        uint32_t new_" + arg_name + "_data = 0;\n"
                                    "        uint32_t new_" + arg_name + "_len = 0;\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct, &new_" + arg_name + "_data, 4);\n"
                                    "        _wasm_instance->read_memory(" + arg_name + "_struct + 4, &new_" + arg_name + "_len, 4);\n"
                                    "        std::vector<ValT_" + arg_name + "> new_" + arg_name + "_flat(new_" + arg_name + "_len);\n"
                                    "        _wasm_instance->read_memory(new_" + arg_name + "_data, new_" + arg_name + "_flat.data(), new_" + arg_name + "_len * sizeof(ValT_" + arg_name + "));\n"
                                    "        " + arg_name + ".clear();\n"
                                    "        " + arg_name + ".insert(new_" + arg_name + "_flat.begin(), new_" + arg_name + "_flat.end());\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_struct);\n"
                                    "        _wasm_instance->deallocate(" + arg_name + "_data);\n"
                                    "        if (new_" + arg_name + "_data != " + arg_name + "_data) _wasm_instance->deallocate(new_" + arg_name + "_data);\n";
                            } else {
                                out << "        _args.push_back(std::to_string(" << arg_name << "));\n";
                            }
                        }
                        out << serialize_pre_call;
                        if (return_type_str == "void") {
                            out << "        _wasm_instance->call_args(\"" << class_name << "_" << name << "\", _args);\n";
                        } else {
                            out << "        auto _ret = _wasm_instance->call_args_int(\"" << class_name << "_" << name << "\", _args);\n";
                        }
                        out << serialize_post_call;
                    } else {
                        if (return_type_str == "void") {
                            out << "        _wasm_instance->call(\"" << class_name << "_" << name << "\", _wasm_ptr);\n";
                        } else {
                            out << "        auto _ret = _wasm_instance->call_int(\"" << class_name << "_" << name << "\", _wasm_ptr);\n";
                        }
                    }
                    
                    template for (constexpr auto m2 : data_members) {
                        if constexpr (std::meta::has_identifier(m2)) {
                            out << "        sync_" << std::meta::identifier_of(m2) << "();\n";
                        }
                    }
                    if (return_type_str != "void") {
                        out << "        return _ret;\n";
                    }
                    out << "    }\n\n";
                }
            }
        }
    }
    out << "};\n";
}

template<typename T>
void generate_wasm_exports(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly EXPORT Generator ---\n";
    out << "#include <emscripten.h>\n\n";
    out << "extern \"C\" {\n\n";
    
    if constexpr (!std::is_abstract_v<T>) {
        out << "EMSCRIPTEN_KEEPALIVE " << class_name << "* " << class_name << "_create() {\n";
        out << "    return new " << class_name << "();\n";
        out << "}\n\n";
    }

    out << "EMSCRIPTEN_KEEPALIVE void " << class_name << "_destroy(" << class_name << "* ptr) {\n";
    out << "    delete ptr;\n";
    out << "}\n\n";

    // Data getters and setters (for marshal by value)
    constexpr static const auto data_members = std::define_static_array(get_marshalled_members(type_info));
    template for (constexpr auto mem : data_members) {
        if constexpr (std::meta::has_identifier(mem)) {
            if constexpr (!member_has_annotation<cerridwen::marshal_by_ref>(mem)) {
                std::string_view name = std::meta::identifier_of(mem);
                // For a robust system, we would map the C++ type to a C API type.
                // For this prototype, we'll assume it's `int` for simplicity if not known, or we can use `auto`.
                // Emscripten C API requires exact types for WebAssembly though. We'll use `int` as a fallback or extract the type name.
                std::string_view type_name = get_type_name(std::meta::type_of(mem));
                out << "EMSCRIPTEN_KEEPALIVE " << type_name << " " << class_name << "_get_" << name << "(" << class_name << "* ptr) {\n";
                out << "    return ptr->" << name << ";\n";
                out << "}\n\n";
                
                out << "EMSCRIPTEN_KEEPALIVE void " << class_name << "_set_" << name << "(" << class_name << "* ptr, " << type_name << " val) {\n";
                out << "    ptr->" << name << " = val;\n";
                out << "}\n\n";
            }
        }
    }

    // Virtual Methods
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    while (return_type_str.find("std::__cxx11::") != std::string::npos) {
                        return_type_str.replace(return_type_str.find("std::__cxx11::"), 14, "std::");
                    }
                    
                    std::string param_list_decl = std::string(class_name) + "* ptr";
                    std::string param_list_call = "";
                    std::string deserialize_pre_call = "";
                    std::string serialize_post_call = "";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        while (p_type.find("std::__cxx11::") != std::string::npos) {
                            p_type.replace(p_type.find("std::__cxx11::"), 14, "std::");
                        }
                        std::string arg_name = "arg" + std::to_string(p_idx);
                        if (p_idx > 0) param_list_call += ", ";

                        if (p_type.find("std::vector") != std::string::npos && p_type.find("&") != std::string::npos) {
                            param_list_decl += ", uint32_t " + arg_name;
                            param_list_call += "local_" + arg_name;
                            
                            deserialize_pre_call +=
                                "    using BaseT_" + arg_name + " = std::remove_reference_t<" + p_type + ">;\n"
                                "    using ValT_" + arg_name + " = BaseT_" + arg_name + "::value_type;\n"
                                "    uint32_t* " + arg_name + "_struct = reinterpret_cast<uint32_t*>(" + arg_name + ");\n"
                                "    ValT_" + arg_name + "* " + arg_name + "_data = reinterpret_cast<ValT_" + arg_name + "*>(" + arg_name + "_struct[0]);\n"
                                "    uint32_t " + arg_name + "_len = " + arg_name + "_struct[1];\n"
                                "    BaseT_" + arg_name + " local_" + arg_name + "(" + arg_name + "_data, " + arg_name + "_data + " + arg_name + "_len);\n";
                            
                            serialize_post_call +=
                                "    ValT_" + arg_name + "* new_" + arg_name + "_data = (ValT_" + arg_name + "*) cerridwen::plugin::allocate(local_" + arg_name + ".size() * sizeof(ValT_" + arg_name + "));\n"
                                "    std::memcpy((void*)new_" + arg_name + "_data, local_" + arg_name + ".data(), local_" + arg_name + ".size() * sizeof(ValT_" + arg_name + "));\n"
                                "    " + arg_name + "_struct[0] = reinterpret_cast<uint32_t>(new_" + arg_name + "_data);\n"
                                "    " + arg_name + "_struct[1] = local_" + arg_name + ".size();\n";
                        } else if ((p_type.find("std::map") != std::string::npos || p_type.find("std::unordered_map") != std::string::npos) && p_type.find("&") != std::string::npos) {
                            param_list_decl += ", uint32_t " + arg_name;
                            param_list_call += "local_" + arg_name;
                            
                            deserialize_pre_call +=
                                "    using BaseT_" + arg_name + " = std::remove_reference_t<" + p_type + ">;\n"
                                "    using K_" + arg_name + " = BaseT_" + arg_name + "::key_type;\n"
                                "    using V_" + arg_name + " = BaseT_" + arg_name + "::mapped_type;\n"
                                "    using PairT_" + arg_name + " = std::pair<K_" + arg_name + ", V_" + arg_name + ">;\n"
                                "    uint32_t* " + arg_name + "_struct = reinterpret_cast<uint32_t*>(" + arg_name + ");\n"
                                "    PairT_" + arg_name + "* " + arg_name + "_data = reinterpret_cast<PairT_" + arg_name + "*>(" + arg_name + "_struct[0]);\n"
                                "    uint32_t " + arg_name + "_len = " + arg_name + "_struct[1];\n"
                                "    BaseT_" + arg_name + " local_" + arg_name + "(" + arg_name + "_data, " + arg_name + "_data + " + arg_name + "_len);\n";
                            
                            serialize_post_call +=
                                "    std::vector<PairT_" + arg_name + "> new_" + arg_name + "_flat(local_" + arg_name + ".begin(), local_" + arg_name + ".end());\n"
                                "    PairT_" + arg_name + "* new_" + arg_name + "_data = (PairT_" + arg_name + "*) cerridwen::plugin::allocate(new_" + arg_name + "_flat.size() * sizeof(PairT_" + arg_name + "));\n"
                                "    std::memcpy((void*)new_" + arg_name + "_data, new_" + arg_name + "_flat.data(), new_" + arg_name + "_flat.size() * sizeof(PairT_" + arg_name + "));\n"
                                "    " + arg_name + "_struct[0] = reinterpret_cast<uint32_t>(new_" + arg_name + "_data);\n"
                                "    " + arg_name + "_struct[1] = new_" + arg_name + "_flat.size();\n";
                        } else if ((p_type.find("list") != std::string::npos || p_type.find("deque") != std::string::npos) && p_type.find("&") != std::string::npos && p_type.find("std::") != std::string::npos) {
                            param_list_decl += ", uint32_t " + arg_name;
                            param_list_call += "local_" + arg_name;
                            
                            deserialize_pre_call +=
                                "    using BaseT_" + arg_name + " = std::remove_reference_t<" + p_type + ">;\n"
                                "    using ValT_" + arg_name + " = BaseT_" + arg_name + "::value_type;\n"
                                "    uint32_t* " + arg_name + "_struct = reinterpret_cast<uint32_t*>(" + arg_name + ");\n"
                                "    ValT_" + arg_name + "* " + arg_name + "_data = reinterpret_cast<ValT_" + arg_name + "*>(" + arg_name + "_struct[0]);\n"
                                "    uint32_t " + arg_name + "_len = " + arg_name + "_struct[1];\n"
                                "    BaseT_" + arg_name + " local_" + arg_name + "(" + arg_name + "_data, " + arg_name + "_data + " + arg_name + "_len);\n";
                            
                            serialize_post_call +=
                                "    std::vector<ValT_" + arg_name + "> new_" + arg_name + "_flat(local_" + arg_name + ".begin(), local_" + arg_name + ".end());\n"
                                "    ValT_" + arg_name + "* new_" + arg_name + "_data = (ValT_" + arg_name + "*) cerridwen::plugin::allocate(new_" + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                "    std::memcpy((void*)new_" + arg_name + "_data, new_" + arg_name + "_flat.data(), new_" + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                "    " + arg_name + "_struct[0] = reinterpret_cast<uint32_t>(new_" + arg_name + "_data);\n"
                                "    " + arg_name + "_struct[1] = new_" + arg_name + "_flat.size();\n";
                        } else if ((p_type.find("set") != std::string::npos || p_type.find("unordered_set") != std::string::npos) && p_type.find("&") != std::string::npos && p_type.find("std::") != std::string::npos) {
                            param_list_decl += ", uint32_t " + arg_name;
                            param_list_call += "local_" + arg_name;
                            
                            deserialize_pre_call +=
                                "    using BaseT_" + arg_name + " = std::remove_reference_t<" + p_type + ">;\n"
                                "    using ValT_" + arg_name + " = BaseT_" + arg_name + "::value_type;\n"
                                "    uint32_t* " + arg_name + "_struct = reinterpret_cast<uint32_t*>(" + arg_name + ");\n"
                                "    ValT_" + arg_name + "* " + arg_name + "_data = reinterpret_cast<ValT_" + arg_name + "*>(" + arg_name + "_struct[0]);\n"
                                "    uint32_t " + arg_name + "_len = " + arg_name + "_struct[1];\n"
                                "    BaseT_" + arg_name + " local_" + arg_name + "(" + arg_name + "_data, " + arg_name + "_data + " + arg_name + "_len);\n";
                            
                            serialize_post_call +=
                                "    std::vector<ValT_" + arg_name + "> new_" + arg_name + "_flat(local_" + arg_name + ".begin(), local_" + arg_name + ".end());\n"
                                "    ValT_" + arg_name + "* new_" + arg_name + "_data = (ValT_" + arg_name + "*) cerridwen::plugin::allocate(new_" + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                "    std::memcpy((void*)new_" + arg_name + "_data, new_" + arg_name + "_flat.data(), new_" + arg_name + "_flat.size() * sizeof(ValT_" + arg_name + "));\n"
                                "    " + arg_name + "_struct[0] = reinterpret_cast<uint32_t>(new_" + arg_name + "_data);\n"
                                "    " + arg_name + "_struct[1] = new_" + arg_name + "_flat.size();\n";
                        } else {
                            param_list_decl += ", " + p_type + " " + arg_name;
                            param_list_call += arg_name;
                        }
                        p_idx++;
                    }

                    if (return_type_str == "void") {
                        out << "EMSCRIPTEN_KEEPALIVE void " << class_name << "_" << name << "(" << param_list_decl << ") {\n";
                        out << deserialize_pre_call;
                        if (p_idx > 0) out << "    ptr->" << name << "(" << param_list_call << ");\n";
                        else out << "    ptr->" << name << "();\n";
                        out << serialize_post_call;
                        out << "}\n\n";
                    } else {
                        out << "EMSCRIPTEN_KEEPALIVE " << return_type_str << " " << class_name << "_" << name << "(" << param_list_decl << ") {\n";
                        out << deserialize_pre_call;
                        if (p_idx > 0) out << "    auto _ret = ptr->" << name << "(" << param_list_call << ");\n";
                        else out << "    auto _ret = ptr->" << name << "();\n";
                        out << serialize_post_call;
                        out << "    return _ret;\n";
                        out << "}\n\n";
                    }
                }
            }
        }
    }
    
    out << "} // extern \"C\"\n";
}

} // namespace meta_impl

namespace meta_impl {

// Map C++ type to Wasm3 signature char
consteval char get_wasm3_sig_char(std::meta::info type_info) {
    std::string_view type_name = std::meta::display_string_of(type_info);
    if (type_name == "void") return 'v';
    if (type_name == "int" || type_name == "uint32_t" || type_name == "int32_t") return 'i';
    if (type_name == "long long" || type_name == "uint64_t" || type_name == "int64_t") return 'I';
    if (type_name == "float") return 'f';
    if (type_name == "double") return 'F';
    // Container references are passed as WASM 32-bit pointers (uint32_t) to a struct { uint32_t ptr; uint32_t len; }
    if (type_name.find("std::vector") != std::string::npos && type_name.find("&") != std::string::npos) return 'i';
    if ((type_name.find("std::map") != std::string::npos || type_name.find("std::unordered_map") != std::string::npos) && type_name.find("&") != std::string::npos) return 'i';
    if ((type_name.find("list") != std::string::npos || type_name.find("deque") != std::string::npos) && type_name.find("&") != std::string::npos && type_name.find("std::") != std::string::npos) return 'i';
    if ((type_name.find("set") != std::string::npos || type_name.find("unordered_set") != std::string::npos) && type_name.find("&") != std::string::npos && type_name.find("std::") != std::string::npos) return 'i';
    if (type_name.find('*') != std::string::npos) return 'i';
    return 'i'; // Default to i32 for enums/etc
}

// Generate the WASM side proxy for a Host exported class
template<typename T>
void generate_host_trampoline(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---\n";
    out << "#include <memory>\n";
    out << "extern \"C\" {\n";
    
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    std::string param_list_decl = "uint64_t ptr";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        param_list_decl += ", " + p_type + " arg" + std::to_string(p_idx);
                        p_idx++;
                    }
                    
                    out << "    __attribute__((import_module(\"env\"), import_name(\"" << class_name << "_" << name << "\")))\n";
                    out << "    " << return_type_str << " " << class_name << "_" << name << "(" << param_list_decl << ");\n";
                }
            }
        }
    }
    out << "    __attribute__((import_module(\"env\"), import_name(\"" << class_name << "_shared_release\")))\n";
    out << "    void " << class_name << "_shared_release(uint64_t handle);\n";
    out << "    __attribute__((import_module(\"env\"), import_name(\"" << class_name << "_shared_clone\")))\n";
    out << "    uint64_t " << class_name << "_shared_clone(uint64_t handle);\n";
    out << "    __attribute__((import_module(\"env\"), import_name(\"" << class_name << "_shared_get_raw\")))\n";
    out << "    uint64_t " << class_name << "_shared_get_raw(uint64_t handle);\n";
    out << "}\n\n";

    out << "class " << class_name << "_Proxy : public " << class_name << " {\n";
    out << "public:\n";
    out << "    uint64_t _host_ptr = 0;\n";
    out << "    " << class_name << "_Proxy(uint64_t p = 0) : _host_ptr(p) {}\n";
    out << "    // Re-targets this proxy at a (different) host object\n";
    out << "    void cerridwen_bind(uint64_t p) { _host_ptr = p; }\n\n";
    
    emitted_methods.clear();
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    std::string param_list_decl = "";
                    std::string param_list_call = "";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        if (p_idx > 0) param_list_decl += ", ";
                        param_list_decl += p_type + " arg" + std::to_string(p_idx);
                        param_list_call += ", arg" + std::to_string(p_idx);
                        p_idx++;
                    }
                    
                    out << "    " << return_type_str << " " << name << "(" << param_list_decl << ") override {\n";
                    if (return_type_str == "void") {
                        out << "        " << class_name << "_" << name << "(_host_ptr" << param_list_call << ");\n";
                    } else {
                        out << "        return " << class_name << "_" << name << "(_host_ptr" << param_list_call << ");\n";
                    }
                    out << "    }\n";
                }
            }
        }
    }
    out << "};\n\n";

    out << "class " << class_name << "_SharedProxy : public " << class_name << "_Proxy {\n";
    out << "public:\n";
    out << "    uint64_t _shared_handle = 0;\n";
    out << "    " << class_name << "_SharedProxy(uint64_t handle = 0) : " << class_name << "_Proxy(handle ? " << class_name << "_shared_get_raw(handle) : 0), _shared_handle(handle) {}\n";
    out << "    " << class_name << "_SharedProxy(const " << class_name << "_SharedProxy& other) : " << class_name << "_Proxy(other._host_ptr) {\n";
    out << "        if (other._shared_handle) {\n";
    out << "            _shared_handle = " << class_name << "_shared_clone(other._shared_handle);\n";
    out << "        }\n";
    out << "    }\n";
    out << "    " << class_name << "_SharedProxy& operator=(const " << class_name << "_SharedProxy& other) {\n";
    out << "        if (this != &other) {\n";
    out << "            if (_shared_handle) " << class_name << "_shared_release(_shared_handle);\n";
    out << "            _host_ptr = other._host_ptr;\n";
    out << "            _shared_handle = other._shared_handle ? " << class_name << "_shared_clone(other._shared_handle) : 0;\n";
    out << "        }\n";
    out << "        return *this;\n";
    out << "    }\n";
    out << "    ~" << class_name << "_SharedProxy() override {\n";
    out << "        if (_shared_handle) {\n";
    out << "            " << class_name << "_shared_release(_shared_handle);\n";
    out << "        }\n";
    out << "    }\n";
    out << "};\n";
}

// Generate the C++ side wrappers that bind to Wasm3
template<typename T>
void generate_host_exports(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly HOST-EXPORTS Generator ---\n";
    out << "#include <wasm3.h>\n";
    out << "#include <m3_env.h>\n";
    out << "#include <memory>\n\n";
    
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    out << "[[maybe_unused]] static m3ApiRawFunction(" << class_name << "_" << name << "_wrapper) {\n";
                    if (return_type_str != "void") {
                        out << "    m3ApiReturnType(" << return_type_str << ");\n";
                    }
                    out << "    m3ApiGetArg(uint64_t, host_ptr);\n";
                    
                    std::string param_list_call = "";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        if (p_type == "const char*" || p_type == "char*") {
                            out << "    m3ApiGetArgMem(" << p_type << ", arg" << p_idx << ");\n";
                        } else {
                            out << "    m3ApiGetArg(" << p_type << ", arg" << p_idx << ");\n";
                        }
                        if (p_idx > 0) param_list_call += ", ";
                        param_list_call += "arg" + std::to_string(p_idx);
                        p_idx++;
                    }
                    
                    out << "    " << class_name << "* obj = reinterpret_cast<" << class_name << "*>(static_cast<uintptr_t>(host_ptr));\n";
                    
                    // Catch C++ exceptions safely
                    out << "    try {\n";
                    if (return_type_str == "void") {
                        out << "        obj->" << name << "(" << param_list_call << ");\n";
                        out << "        m3ApiSuccess();\n";
                    } else {
                        out << "        " << return_type_str << " ret = obj->" << name << "(" << param_list_call << ");\n";
                        out << "        m3ApiReturn(ret);\n";
                    }
                    out << "    } catch (const cerridwen::PluginException& e) {\n";
                    out << "        cerridwen::record_plugin_error(e.what());\n";
                    out << "        m3ApiTrap(\"cerridwen:plugin_exception\");\n";
                    out << "    } catch (const std::exception& e) {\n";
                    out << "        cerridwen::record_host_error(e.what());\n";
                    out << "        m3ApiTrap(\"cerridwen:host_exception\");\n";
                    out << "    } catch (...) {\n";
                    out << "        cerridwen::record_host_error(\"Unknown C++ exception in host method " << class_name << "::" << name << "\");\n";
                    out << "        m3ApiTrap(\"cerridwen:host_exception\");\n";
                    out << "    }\n";
                    
                    out << "}\n\n";
                }
            }
        }
    }
    
    out << "[[maybe_unused]] static m3ApiRawFunction(" << class_name << "_shared_release) {\n";
    out << "    m3ApiGetArg(uint64_t, handle);\n";
    out << "    auto* sptr = reinterpret_cast<std::shared_ptr<" << class_name << ">*>(static_cast<uintptr_t>(handle));\n";
    out << "    delete sptr;\n";
    out << "    m3ApiSuccess();\n";
    out << "}\n\n";

    out << "[[maybe_unused]] static m3ApiRawFunction(" << class_name << "_shared_clone) {\n";
    out << "    m3ApiReturnType(uint64_t);\n";
    out << "    m3ApiGetArg(uint64_t, handle);\n";
    out << "    auto* sptr = reinterpret_cast<std::shared_ptr<" << class_name << ">*>(static_cast<uintptr_t>(handle));\n";
    out << "    auto* new_sptr = new std::shared_ptr<" << class_name << ">(*sptr);\n";
    out << "    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(new_sptr)));\n";
    out << "}\n\n";

    out << "[[maybe_unused]] static m3ApiRawFunction(" << class_name << "_shared_get_raw) {\n";
    out << "    m3ApiReturnType(uint64_t);\n";
    out << "    m3ApiGetArg(uint64_t, handle);\n";
    out << "    auto* sptr = reinterpret_cast<std::shared_ptr<" << class_name << ">*>(static_cast<uintptr_t>(handle));\n";
    out << "    m3ApiReturn(static_cast<uint64_t>(reinterpret_cast<uintptr_t>(sptr->get())));\n";
    out << "}\n\n";

    // Generate binder function
    out << "inline void bind_" << class_name << "(IM3Module module) {\n";
    emitted_methods.clear();
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    
                    std::string sig = "";
                    sig += get_wasm3_sig_char(return_t);
                    sig += "(I"; // first arg is host_ptr (i64)
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        sig += get_wasm3_sig_char(p);
                    }
                    sig += ")";
                    
                    out << "    {\n";
                    out << "        M3Result res = m3_LinkRawFunction(module, \"env\", \"" << class_name << "_" << name << "\", \"" << sig << "\", &" << class_name << "_" << name << "_wrapper);\n";
                    out << "        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string(\"m3_LinkRawFunction failed for \") + \"" << class_name << "_" << name << ": \" + res);\n";
                    out << "    }\n";
                }
            }
        }
    }
    out << "    {\n";
    out << "        M3Result res = m3_LinkRawFunction(module, \"env\", \"" << class_name << "_shared_release\", \"v(I)\", &" << class_name << "_shared_release);\n";
    out << "        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string(\"m3_LinkRawFunction failed for \") + \"" << class_name << "_shared_release: \" + res);\n";
    out << "    }\n";
    out << "    {\n";
    out << "        M3Result res = m3_LinkRawFunction(module, \"env\", \"" << class_name << "_shared_clone\", \"I(I)\", &" << class_name << "_shared_clone);\n";
    out << "        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string(\"m3_LinkRawFunction failed for \") + \"" << class_name << "_shared_clone: \" + res);\n";
    out << "    }\n";
    out << "    {\n";
    out << "        M3Result res = m3_LinkRawFunction(module, \"env\", \"" << class_name << "_shared_get_raw\", \"I(I)\", &" << class_name << "_shared_get_raw);\n";
    out << "        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string(\"m3_LinkRawFunction failed for \") + \"" << class_name << "_shared_get_raw: \" + res);\n";
    out << "    }\n";
    out << "}\n\n";
}

} // namespace meta_impl

} // namespace cerridwen
