#pragma once

#include <cerridwen/annotations.hpp>
#include <cerridwen/exporter.hpp>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>
#include <meta>

namespace cerridwen {

namespace meta_impl {

struct MethodMeta {
    std::string name;
    std::string return_type;
    bool is_virtual;
    bool is_const;
    std::vector<std::string> param_types;
};

// Extracts name of a type robustly
consteval std::string_view get_type_name(std::meta::info type_info) {
    if (std::meta::has_identifier(type_info)) {
        return std::meta::identifier_of(type_info);
    }
    return std::meta::display_string_of(type_info);
}

consteval std::vector<std::meta::info> get_all_virtual_functions(std::meta::info t) {
    std::vector<std::meta::info> res;
    for (auto mem : std::meta::members_of(t, std::meta::access_context::unchecked())) {
        if (std::meta::is_function(mem) && std::meta::is_virtual(mem) && !std::meta::is_constructor(mem) && !std::meta::is_destructor(mem)) {
            res.push_back(mem);
        }
    }
    for (auto base : std::meta::bases_of(t, std::meta::access_context::unchecked())) {
        auto base_funcs = get_all_virtual_functions(std::meta::type_of(base));
        res.insert(res.end(), base_funcs.begin(), base_funcs.end());
    }
    return res;
}

// Data members that opted into marshalling (marshal_by_value / marshal_by_ref).
// Unannotated members are private plugin state and never cross the boundary.
consteval std::vector<std::meta::info> get_marshalled_members(std::meta::info t) {
    std::vector<std::meta::info> res;
    for (auto m : std::meta::nonstatic_data_members_of(t, std::meta::access_context::unchecked())) {
        if (std::meta::has_identifier(m) &&
            (member_has_annotation<cerridwen::marshal_by_value>(m) || member_has_annotation<cerridwen::marshal_by_ref>(m))) {
            res.push_back(m);
        }
    }
    for (auto base : std::meta::bases_of(t, std::meta::access_context::unchecked())) {
        auto base_members = get_marshalled_members(std::meta::type_of(base));
        res.insert(res.end(), base_members.begin(), base_members.end());
    }
    return res;
}

template<typename T>
void generate_wasm_trampoline(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly TRAMPOLINE Generator ---\n";
    out << "#include <functional>\n";
    out << "#include <mutex>\n";
    out << "#include <stdexcept>\n";
    out << "#include <cerridwen/errors.hpp>\n";
    out << "#include <cerridwen/plugin_manager.hpp>\n\n";
    out << "class " << class_name << "_Trampoline : public " << class_name << " {\n";
    out << "public:\n";
    out << "    cerridwen::WasmInstance* _wasm_instance = nullptr;\n";
    out << "    uint32_t _wasm_ptr = 0;\n\n";
    
    // Check for thread-safety annotation
    constexpr bool is_thread_safe = member_has_annotation<cerridwen::thread_safe>(type_info);
    if (is_thread_safe) {
        out << "    // Thread Safe Plugin Locking\n";
        out << "    std::mutex _plugin_mutex;\n\n";
    }

    out << "    ~" << class_name << "_Trampoline() override {\n";
    out << "        if (_wasm_instance && _wasm_ptr) {\n";
    out << "            // Call WASM destroy function; a destructor must never throw\n";
    out << "            try { _wasm_instance->call(\"" << class_name << "_destroy\", _wasm_ptr); } catch (...) {}\n";
    out << "        }\n";
    out << "    }\n\n";
    
    out << "    // Inherit constructors\n";
    out << "    using " << class_name << "::" << class_name << ";\n\n";
    
    // Data Marshalling
    constexpr static const auto data_members = std::define_static_array(get_marshalled_members(type_info));
    template for (constexpr auto mem : data_members) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            out << "    // Marshalled property accessors for: " << name << "\n";
            out << "    void sync_" << name << "() {\n";
            if constexpr (member_has_annotation<cerridwen::marshal_by_ref>(mem)) {
                out << "        // [Ref Marshalling] Copy memory directly from WASM linear memory offset\n";
                out << "        // this->" << name << " = _wasm_instance->read_memory( ... );\n";
            } else {
                out << "        // [Value Marshalling] Call WASM getter to retrieve value\n";
                out << "        this->" << name << " = _wasm_instance->call_int(\"" << class_name << "_get_" << name << "\", _wasm_ptr);\n";
            }
            out << "    }\n";
        }
    }

    // Virtual Methods (recursive)
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    std::string param_list_decl = "";
                    std::vector<std::string> param_names;
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        if (p_idx > 0) param_list_decl += ", ";
                        std::string arg_name = "arg" + std::to_string(p_idx);
                        param_list_decl += p_type + " " + arg_name;
                        param_names.push_back(arg_name);
                        p_idx++;
                    }

                    out << "    " << return_type_str << " " << name << "(" << param_list_decl << ") override {\n";
                    if (is_thread_safe) {
                        out << "        std::lock_guard<std::mutex> lock(_plugin_mutex);\n";
                    }
                    out << "        if (!_wasm_instance) throw std::runtime_error(\"No WASM instance\");\n";
                    out << "        // Sync data before call\n";
                    template for (constexpr auto m2 : data_members) {
                        if constexpr (std::meta::has_identifier(m2)) {
                            std::string_view m2_name = std::meta::identifier_of(m2);
                            if constexpr (!member_has_annotation<cerridwen::marshal_by_ref>(m2)) {
                                out << "        _wasm_instance->call_set_int(\"" << class_name << "_set_" << m2_name << "\", _wasm_ptr, this->" << m2_name << ");\n";
                            }
                        }
                    }
                    
                    if (p_idx > 0) {
                        out << "        std::vector<std::string> _args;\n";
                        out << "        _args.push_back(std::to_string(_wasm_ptr));\n";
                        for (const auto& arg_name : param_names) {
                            out << "        _args.push_back(std::to_string(" << arg_name << "));\n";
                        }
                        if (return_type_str == "void") {
                            out << "        _wasm_instance->call_args(\"" << class_name << "_" << name << "\", _args);\n";
                        } else {
                            out << "        auto _ret = _wasm_instance->call_args_int(\"" << class_name << "_" << name << "\", _args);\n";
                        }
                    } else {
                        if (return_type_str == "void") {
                            out << "        _wasm_instance->call(\"" << class_name << "_" << name << "\", _wasm_ptr);\n";
                        } else {
                            out << "        auto _ret = _wasm_instance->call_int(\"" << class_name << "_" << name << "\", _wasm_ptr);\n";
                        }
                    }
                    
                    template for (constexpr auto m2 : data_members) {
                        if constexpr (std::meta::has_identifier(m2)) {
                            out << "        sync_" << std::meta::identifier_of(m2) << "();\n";
                        }
                    }
                    if (return_type_str != "void") {
                        out << "        return _ret;\n";
                    }
                    out << "    }\n\n";
                }
            }
        }
    }
    out << "};\n";
}

template<typename T>
void generate_wasm_exports(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly EXPORT Generator ---\n";
    out << "#include <emscripten.h>\n\n";
    out << "extern \"C\" {\n\n";
    
    if constexpr (!std::is_abstract_v<T>) {
        out << "EMSCRIPTEN_KEEPALIVE " << class_name << "* " << class_name << "_create() {\n";
        out << "    return new " << class_name << "();\n";
        out << "}\n\n";
    }

    out << "EMSCRIPTEN_KEEPALIVE void " << class_name << "_destroy(" << class_name << "* ptr) {\n";
    out << "    delete ptr;\n";
    out << "}\n\n";

    // Data getters and setters (for marshal by value)
    constexpr static const auto data_members = std::define_static_array(get_marshalled_members(type_info));
    template for (constexpr auto mem : data_members) {
        if constexpr (std::meta::has_identifier(mem)) {
            if constexpr (!member_has_annotation<cerridwen::marshal_by_ref>(mem)) {
                std::string_view name = std::meta::identifier_of(mem);
                // For a robust system, we would map the C++ type to a C API type.
                // For this prototype, we'll assume it's `int` for simplicity if not known, or we can use `auto`.
                // Emscripten C API requires exact types for WebAssembly though. We'll use `int` as a fallback or extract the type name.
                std::string_view type_name = get_type_name(std::meta::type_of(mem));
                out << "EMSCRIPTEN_KEEPALIVE " << type_name << " " << class_name << "_get_" << name << "(" << class_name << "* ptr) {\n";
                out << "    return ptr->" << name << ";\n";
                out << "}\n\n";
                
                out << "EMSCRIPTEN_KEEPALIVE void " << class_name << "_set_" << name << "(" << class_name << "* ptr, " << type_name << " val) {\n";
                out << "    ptr->" << name << " = val;\n";
                out << "}\n\n";
            }
        }
    }

    // Virtual Methods
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    std::string param_list_decl = std::string(class_name) + "* ptr";
                    std::string param_list_call = "";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        param_list_decl += ", " + p_type + " arg" + std::to_string(p_idx);
                        if (p_idx > 0) param_list_call += ", ";
                        param_list_call += "arg" + std::to_string(p_idx);
                        p_idx++;
                    }

                    if (return_type_str == "void") {
                        out << "EMSCRIPTEN_KEEPALIVE void " << class_name << "_" << name << "(" << param_list_decl << ") {\n";
                        if (p_idx > 0) out << "    ptr->" << name << "(" << param_list_call << ");\n";
                        else out << "    ptr->" << name << "();\n";
                        out << "}\n\n";
                    } else {
                        out << "EMSCRIPTEN_KEEPALIVE " << return_type_str << " " << class_name << "_" << name << "(" << param_list_decl << ") {\n";
                        if (p_idx > 0) out << "    return ptr->" << name << "(" << param_list_call << ");\n";
                        else out << "    return ptr->" << name << "();\n";
                        out << "}\n\n";
                    }
                }
            }
        }
    }
    
    out << "} // extern \"C\"\n";
}

} // namespace meta_impl

namespace meta_impl {

// Map C++ type to Wasm3 signature char
consteval char get_wasm3_sig_char(std::meta::info type_info) {
    std::string_view type_name = std::meta::display_string_of(type_info);
    if (type_name == "void") return 'v';
    if (type_name == "int" || type_name == "uint32_t" || type_name == "int32_t") return 'i';
    if (type_name == "long long" || type_name == "uint64_t" || type_name == "int64_t") return 'I';
    if (type_name == "float") return 'f';
    if (type_name == "double") return 'F';
    if (type_name.find('*') != std::string::npos) return 'i';
    return 'i'; // Default to i32 for enums/etc
}

// Generate the WASM side proxy for a Host exported class
template<typename T>
void generate_host_trampoline(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly HOST-PROXY Generator ---\n";
    out << "extern \"C\" {\n";
    
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    std::string param_list_decl = "uint64_t ptr";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        param_list_decl += ", " + p_type + " arg" + std::to_string(p_idx);
                        p_idx++;
                    }
                    
                    out << "    __attribute__((import_module(\"env\"), import_name(\"" << class_name << "_" << name << "\")))\n";
                    out << "    " << return_type_str << " " << class_name << "_" << name << "(" << param_list_decl << ");\n";
                }
            }
        }
    }
    out << "}\n\n";

    out << "class " << class_name << "_Proxy : public " << class_name << " {\n";
    out << "public:\n";
    out << "    uint64_t _host_ptr = 0;\n";
    out << "    " << class_name << "_Proxy(uint64_t p = 0) : _host_ptr(p) {}\n";
    out << "    // Re-targets this proxy at a (different) host object\n";
    out << "    void cerridwen_bind(uint64_t p) { _host_ptr = p; }\n\n";
    
    emitted_methods.clear();
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    std::string param_list_decl = "";
                    std::string param_list_call = "";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        if (p_idx > 0) param_list_decl += ", ";
                        param_list_decl += p_type + " arg" + std::to_string(p_idx);
                        param_list_call += ", arg" + std::to_string(p_idx);
                        p_idx++;
                    }
                    
                    out << "    " << return_type_str << " " << name << "(" << param_list_decl << ") override {\n";
                    if (return_type_str == "void") {
                        out << "        " << class_name << "_" << name << "(_host_ptr" << param_list_call << ");\n";
                    } else {
                        out << "        return " << class_name << "_" << name << "(_host_ptr" << param_list_call << ");\n";
                    }
                    out << "    }\n";
                }
            }
        }
    }
    out << "};\n";
}

// Generate the C++ side wrappers that bind to Wasm3
template<typename T>
void generate_host_exports(std::ostream& out, std::string_view class_name) {
    constexpr auto type_info = ^^T;
    
    out << "// --- Generated by Cerridwen WebAssembly HOST-EXPORTS Generator ---\n";
    out << "#include <wasm3.h>\n";
    out << "#include <m3_env.h>\n\n";
    
    constexpr static const auto all_methods = std::define_static_array(get_all_virtual_functions(type_info));
    std::vector<std::string> emitted_methods;
    
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    std::string return_type_str = std::string(std::meta::display_string_of(return_t));
                    
                    out << "[[maybe_unused]] static m3ApiRawFunction(" << class_name << "_" << name << "_wrapper) {\n";
                    if (return_type_str != "void") {
                        out << "    m3ApiReturnType(" << return_type_str << ");\n";
                    }
                    out << "    m3ApiGetArg(uint64_t, host_ptr);\n";
                    
                    std::string param_list_call = "";
                    int p_idx = 0;
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        std::string p_type = std::string(std::meta::display_string_of(p));
                        if (p_type == "const char*" || p_type == "char*") {
                            out << "    m3ApiGetArgMem(" << p_type << ", arg" << p_idx << ");\n";
                        } else {
                            out << "    m3ApiGetArg(" << p_type << ", arg" << p_idx << ");\n";
                        }
                        if (p_idx > 0) param_list_call += ", ";
                        param_list_call += "arg" + std::to_string(p_idx);
                        p_idx++;
                    }
                    
                    out << "    " << class_name << "* obj = reinterpret_cast<" << class_name << "*>(static_cast<uintptr_t>(host_ptr));\n";
                    
                    // Catch C++ exceptions safely
                    out << "    try {\n";
                    if (return_type_str == "void") {
                        out << "        obj->" << name << "(" << param_list_call << ");\n";
                        out << "        m3ApiSuccess();\n";
                    } else {
                        out << "        " << return_type_str << " ret = obj->" << name << "(" << param_list_call << ");\n";
                        out << "        m3ApiReturn(ret);\n";
                    }
                    out << "    } catch (const cerridwen::PluginException& e) {\n";
                    out << "        cerridwen::record_plugin_error(e.what());\n";
                    out << "        m3ApiTrap(\"cerridwen:plugin_exception\");\n";
                    out << "    } catch (const std::exception& e) {\n";
                    out << "        cerridwen::record_host_error(e.what());\n";
                    out << "        m3ApiTrap(\"cerridwen:host_exception\");\n";
                    out << "    } catch (...) {\n";
                    out << "        cerridwen::record_host_error(\"Unknown C++ exception in host method " << class_name << "::" << name << "\");\n";
                    out << "        m3ApiTrap(\"cerridwen:host_exception\");\n";
                    out << "    }\n";
                    
                    out << "}\n\n";
                }
            }
        }
    }
    
    // Generate binder function
    out << "inline void bind_" << class_name << "(IM3Module module) {\n";
    emitted_methods.clear();
    template for (constexpr auto mem : all_methods) {
        if constexpr (std::meta::has_identifier(mem)) {
            std::string_view name = std::meta::identifier_of(mem);
            if (name != "operator=") {
                bool already_emitted = false;
                for (const auto& em : emitted_methods) {
                    if (em == name) { already_emitted = true; break; }
                }
                if (!already_emitted) {
                    emitted_methods.push_back(std::string(name));
                    constexpr auto type_t = std::meta::type_of(mem);
                    constexpr auto return_t = std::meta::return_type_of(type_t);
                    
                    std::string sig = "";
                    sig += get_wasm3_sig_char(return_t);
                    sig += "(I"; // first arg is host_ptr (i64)
                    template for (constexpr auto p : std::define_static_array(std::meta::parameters_of(type_t))) {
                        sig += get_wasm3_sig_char(p);
                    }
                    sig += ")";
                    
                    out << "    {\n";
                    out << "        M3Result res = m3_LinkRawFunction(module, \"env\", \"" << class_name << "_" << name << "\", \"" << sig << "\", &" << class_name << "_" << name << "_wrapper);\n";
                    out << "        if (res && res != m3Err_functionLookupFailed) throw std::runtime_error(std::string(\"m3_LinkRawFunction failed for \") + \"" << class_name << "_" << name << ": \" + res);\n";
                    out << "    }\n";
                }
            }
        }
    }
    out << "}\n\n";
}

} // namespace meta_impl

} // namespace cerridwen
